/*
Zulip REST API

Testing InvitesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api_test

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	
)

func Test_gozulip_InvitesAPIService(t *testing.T) {

	configuration := NewConfiguration()
	apiClient := NewAPIClient(configuration)

	t.Run("Test InvitesAPIService CreateInviteLink", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InvitesAPI.CreateInviteLink(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesAPIService GetInvites", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InvitesAPI.GetInvites(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesAPIService ResendEmailInvite", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inviteId int32

		resp, httpRes, err := apiClient.InvitesAPI.ResendEmailInvite(context.Background(), inviteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesAPIService RevokeEmailInvite", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inviteId int32

		resp, httpRes, err := apiClient.InvitesAPI.RevokeEmailInvite(context.Background(), inviteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesAPIService RevokeInviteLink", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inviteId int32

		resp, httpRes, err := apiClient.InvitesAPI.RevokeInviteLink(context.Background(), inviteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesAPIService SendInvites", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InvitesAPI.SendInvites(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
