/*
Zulip REST API

Testing RemindersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api_test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/tum-zulip/go-zulip/pkg/api"
)

func Test_RemindersAPIService(t *testing.T) {
	runForClients(t, allClients, func(t *testing.T, apiClient *api.ZulipClient) {

		t.Run("CreateMessageReminder", func(t *testing.T) {

			resp, httpRes, err := apiClient.CreateMessageReminder(context.Background()).Execute()

			require.NoError(t, err)
			require.NotNil(t, resp)
			assert.Equal(t, 200, httpRes.StatusCode)

		})

		t.Run("DeleteReminder", func(t *testing.T) {

			var reminderId int32

			resp, httpRes, err := apiClient.DeleteReminder(context.Background(), reminderId).Execute()

			require.NoError(t, err)
			require.NotNil(t, resp)
			assert.Equal(t, 200, httpRes.StatusCode)

		})

		t.Run("GetReminders", func(t *testing.T) {

			resp, httpRes, err := apiClient.GetReminders(context.Background()).Execute()

			require.NoError(t, err)
			require.NotNil(t, resp)
			assert.Equal(t, 200, httpRes.StatusCode)

		})
	})
}
