package mobile

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/tum-zulip/go-zulip/zulip"
	. "github.com/tum-zulip/go-zulip/zulip/internal/apiutils"
)

type APIMobile interface {

	// E2eeTestNotify Send an E2EE test notification to mobile device(s)
	//
	// Trigger sending an end-to-end encrypted (E2EE) test push notification
	// to the user's selected mobile device or all of their mobile devices.
	//
	// *Changes**: New in Zulip 11.0 (feature level 420).
	//
	E2eeTestNotify(ctx context.Context) E2eeTestNotifyRequest

	// E2eeTestNotifyExecute executes the request
	E2eeTestNotifyExecute(r E2eeTestNotifyRequest) (*zulip.Response, *http.Response, error)

	// RegisterPushDevice Register E2EE push device
	//
	// Register a device to receive end-to-end encrypted mobile push notifications.
	//
	// *Changes**: New in Zulip 11.0 (feature level 406).
	//
	RegisterPushDevice(ctx context.Context) RegisterPushDeviceRequest

	// RegisterPushDeviceExecute executes the request
	RegisterPushDeviceExecute(r RegisterPushDeviceRequest) (*zulip.Response, *http.Response, error)

	// TestNotify Send a test notification to mobile device(s)
	//
	// Trigger sending a test push notification to the user's
	// selected mobile device or all of their mobile devices.
	//
	// *Changes**: Starting with Zulip 8.0 (feature level 234), test
	// notifications sent via this endpoint use `test` rather than
	// `test-by-device-token` in the `event` field. Also, as of this
	// feature level, all mobile push notifications now include a
	// `realm_name` field.
	//
	// New in Zulip 8.0 (feature level 217).
	//
	TestNotify(ctx context.Context) TestNotifyRequest

	// TestNotifyExecute executes the request
	TestNotifyExecute(r TestNotifyRequest) (*zulip.Response, *http.Response, error)
}

type mobileService struct {
	client StructuredClient
}

func NewMobileService(client StructuredClient) *mobileService {
	return &mobileService{client: client}
}

var _ APIMobile = (*mobileService)(nil)

type E2eeTestNotifyRequest struct {
	ctx           context.Context
	apiService    APIMobile
	pushAccountId *int64
}

// The push account Id for the device to which to send the test notification.  If this parameter is not submitted, the E2EE test notification will be sent to all of the user's devices registered on the server.  A mobile client should pass this parameter, to avoid triggering a test notification for other clients.  See [`POST /mobile_push/register`] for details on push account Ids.
//
// [`POST /mobile_push/register`]: https://zulip.com/api/register-push-device
func (r E2eeTestNotifyRequest) PushAccountId(pushAccountId int64) E2eeTestNotifyRequest {
	r.pushAccountId = &pushAccountId
	return r
}

func (r E2eeTestNotifyRequest) Execute() (*zulip.Response, *http.Response, error) {
	return r.apiService.E2eeTestNotifyExecute(r)
}

// E2eeTestNotify Send an E2EE test notification to mobile device(s)
//
// Trigger sending an end-to-end encrypted (E2EE) test push notification
// to the user's selected mobile device or all of their mobile devices.
//
// *Changes**: New in Zulip 11.0 (feature level 420).
func (s *mobileService) E2eeTestNotify(ctx context.Context) E2eeTestNotifyRequest {
	return E2eeTestNotifyRequest{
		apiService: s,
		ctx:        ctx,
	}
}

// Execute executes the request
func (s *mobileService) E2eeTestNotifyExecute(r E2eeTestNotifyRequest) (*zulip.Response, *http.Response, error) {
	var (
		method   = http.MethodPost
		headers  = make(map[string]string)
		query    = url.Values{}
		form     = url.Values{}
		response = &zulip.Response{}
		endpoint = "/mobile_push/e2ee/test_notification"
	)
	headers["Content-Type"] = "application/x-www-form-urlencoded"
	headers["Accept"] = "application/json"

	AddOptionalParam(form, "push_account_id", r.pushAccountId)
	req, err := PrepareRequest(r.ctx, s.client, endpoint, method, headers, query, form, nil)
	if err != nil {
		return nil, nil, err
	}

	httpResp, err := s.client.CallAPI(r.ctx, req, response)
	return response, httpResp, err
}

type RegisterPushDeviceRequest struct {
	ctx                       context.Context
	apiService                APIMobile
	tokenKind                 *string
	pushAccountId             *int64
	pushPublicKey             *string
	bouncerPublicKey          *string
	encryptedPushRegistration *string
}

// Whether the token was generated by FCM or APNs.
func (r RegisterPushDeviceRequest) TokenKind(tokenKind string) RegisterPushDeviceRequest {
	r.tokenKind = &tokenKind
	return r
}

// A random integer generated by the client that will be included in mobile push notifications along with encrypted payloads to identify pushes as being related to this registration. Must be unique in the client's table of accounts.
func (r RegisterPushDeviceRequest) PushAccountId(pushAccountId int64) RegisterPushDeviceRequest {
	r.pushAccountId = &pushAccountId
	return r
}

// Public part of the asymmetric key pair generated by the client using NaCl (the Networking and Cryptography Library), encoded using a RFC 4648 standard base64 encoder.  It is used to encrypt notifications for delivery to the client.
func (r RegisterPushDeviceRequest) PushPublicKey(pushPublicKey string) RegisterPushDeviceRequest {
	r.pushPublicKey = &pushPublicKey
	return r
}

// Which of the bouncer's public keys the client used to encrypt the `PushRegistration` dictionary.  When the bouncer rotates the key, a new asymmetric key pair is created, and the new public key is baked into a new client release. Because the bouncer routinely rotates key, this field clarifies which public key the client is using.
func (r RegisterPushDeviceRequest) BouncerPublicKey(bouncerPublicKey string) RegisterPushDeviceRequest {
	r.bouncerPublicKey = &bouncerPublicKey
	return r
}

// Ciphertext generated by encrypting a `PushRegistration` dictionary using the `bouncer_public_key`, encoded using a RFC 4648 standard base64 encoder.  The `PushRegistration` dictionary contains the fields `token`, `token_kind`, `timestamp`, and (for iOS devices) `ios_app_id`. The dictionary is JSON-encoded before encryption.
func (r RegisterPushDeviceRequest) EncryptedPushRegistration(encryptedPushRegistration string) RegisterPushDeviceRequest {
	r.encryptedPushRegistration = &encryptedPushRegistration
	return r
}

func (r RegisterPushDeviceRequest) Execute() (*zulip.Response, *http.Response, error) {
	return r.apiService.RegisterPushDeviceExecute(r)
}

// RegisterPushDevice Register E2EE push device
//
// Register a device to receive end-to-end encrypted mobile push notifications.
//
// *Changes**: New in Zulip 11.0 (feature level 406).
func (s *mobileService) RegisterPushDevice(ctx context.Context) RegisterPushDeviceRequest {
	return RegisterPushDeviceRequest{
		apiService: s,
		ctx:        ctx,
	}
}

// Execute executes the request
func (s *mobileService) RegisterPushDeviceExecute(r RegisterPushDeviceRequest) (*zulip.Response, *http.Response, error) {
	var (
		method   = http.MethodPost
		headers  = make(map[string]string)
		query    = url.Values{}
		form     = url.Values{}
		response = &zulip.Response{}
		endpoint = "/mobile_push/register"
	)
	if r.tokenKind == nil {
		return nil, nil, fmt.Errorf("tokenKind is required and must be specified")
	}
	if r.pushAccountId == nil {
		return nil, nil, fmt.Errorf("pushAccountId is required and must be specified")
	}
	if r.pushPublicKey == nil {
		return nil, nil, fmt.Errorf("pushPublicKey is required and must be specified")
	}
	if r.bouncerPublicKey == nil {
		return nil, nil, fmt.Errorf("bouncerPublicKey is required and must be specified")
	}
	if r.encryptedPushRegistration == nil {
		return nil, nil, fmt.Errorf("encryptedPushRegistration is required and must be specified")
	}

	headers["Content-Type"] = "application/x-www-form-urlencoded"
	headers["Accept"] = "application/json"

	AddParam(form, "token_kind", r.tokenKind)
	AddParam(form, "push_account_id", r.pushAccountId)
	AddParam(form, "push_public_key", r.pushPublicKey)
	AddParam(form, "bouncer_public_key", r.bouncerPublicKey)
	AddParam(form, "encrypted_push_registration", r.encryptedPushRegistration)
	req, err := PrepareRequest(r.ctx, s.client, endpoint, method, headers, query, form, nil)
	if err != nil {
		return nil, nil, err
	}

	httpResp, err := s.client.CallAPI(r.ctx, req, response)
	return response, httpResp, err
}

type TestNotifyRequest struct {
	ctx        context.Context
	apiService APIMobile
	token      *string
}

// The push token for the device to which to send the test notification.  If this parameter is not submitted, the test notification will be sent to all of the user's devices registered on the server.  A mobile client should pass this parameter, to avoid triggering a test notification for other clients.
func (r TestNotifyRequest) Token(token string) TestNotifyRequest {
	r.token = &token
	return r
}

func (r TestNotifyRequest) Execute() (*zulip.Response, *http.Response, error) {
	return r.apiService.TestNotifyExecute(r)
}

// TestNotify Send a test notification to mobile device(s)
//
// Trigger sending a test push notification to the user's
// selected mobile device or all of their mobile devices.
//
// *Changes**: Starting with Zulip 8.0 (feature level 234), test
// notifications sent via this endpoint use `test` rather than
// `test-by-device-token` in the `event` field. Also, as of this
// feature level, all mobile push notifications now include a
// `realm_name` field.
//
// New in Zulip 8.0 (feature level 217).
func (s *mobileService) TestNotify(ctx context.Context) TestNotifyRequest {
	return TestNotifyRequest{
		apiService: s,
		ctx:        ctx,
	}
}

// Execute executes the request
func (s *mobileService) TestNotifyExecute(r TestNotifyRequest) (*zulip.Response, *http.Response, error) {
	var (
		method   = http.MethodPost
		headers  = make(map[string]string)
		query    = url.Values{}
		form     = url.Values{}
		response = &zulip.Response{}
		endpoint = "/mobile_push/test_notification"
	)
	headers["Content-Type"] = "application/x-www-form-urlencoded"
	headers["Accept"] = "application/json"

	AddOptionalParam(form, "token", r.token)
	req, err := PrepareRequest(r.ctx, s.client, endpoint, method, headers, query, form, nil)
	if err != nil {
		return nil, nil, err
	}

	httpResp, err := s.client.CallAPI(r.ctx, req, response)
	return response, httpResp, err
}
