name: Provision Zulip
description: Provision and start a Zulip dev or prod-like instance

inputs:
  zulip_ref:
    description: Zulip git ref (branch/tag/commit)
    required: false
    default: main
  zulip_repo:
    description: Repository to clone Zulip from (in owner/repo format)
    required: false
    default: zulip/zulip
  wait_timeout:
    description: Seconds to wait for Zulip to come up
    required: false
    default: '900'
  cache_epoch_pnpm:
    description: Cache epoch for pnpm
    required: false
    default: '1'
  cache_epoch_uv:
    description: Cache epoch for uv
    required: false
    default: '1'
  cache_epoch_emoji:
    description: Cache epoch for emoji
    required: false
    default: '1'

outputs:
  site_url:
    description: URL to the running Zulip server
    value: ${{ steps.outputs-step.outputs.site_url }}
  log_path:
    description: Path of the Zulip log file on runner
    value: ${{ steps.outputs-step.outputs.log_path }}

runs:
  using: composite
  steps:
    - name: Setup environment
      shell: bash
      run: |
        set -euo pipefail
        {
          echo "PNPM_STORE_PATH=${HOME}/.pnpm-store"
          echo "UV_CACHE_DIR=${HOME}/.cache/uv"
          echo "EMOJI_CACHE_DIR=${HOME}/.cache/zulip-emoji"
          echo "ZULIP_DEV_LOG=$RUNNER_TEMP/zulip-dev.log"
          echo "ZULIP_RUN_PID=$RUNNER_TEMP/zulip-dev.pid"
          # Default dev URL (caller can override via env in the workflow)
          echo "ZULIP_URL=${ZULIP_URL:-http://127.0.0.1:9991}"
        } >> "$GITHUB_ENV"

    - name: Checkout Zulip (ref ${{ inputs.zulip_ref }})
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.zulip_repo }}
        ref: ${{ inputs.zulip_ref }}
        path: zulip

    - name: Create cache directories
      shell: bash
      run: |
        set -euo pipefail
        mkdir -p "${EMOJI_CACHE_DIR}"
        mkdir -p "${PNPM_STORE_PATH}"
        mkdir -p "${UV_CACHE_DIR}"

    - name: Restore pnpm store cache
      uses: actions/cache@v4
      with:
        path: ${{ env.PNPM_STORE_PATH }}
        key: ${{ inputs.cache_epoch_pnpm }}-pnpm-${{ inputs.zulip_ref }}-${{ hashFiles('zulip/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ inputs.cache_epoch_pnpm }}-pnpm-${{ inputs.zulip_ref }}-
          ${{ inputs.cache_epoch_pnpm }}-pnpm-

    - name: Restore uv cache
      uses: actions/cache@v4
      with:
        path: ${{ env.UV_CACHE_DIR }}
        key: ${{ inputs.cache_epoch_uv }}-uv-${{ inputs.zulip_ref }}-${{ hashFiles('zulip/uv.lock') }}
        restore-keys: |
          ${{ inputs.cache_epoch_uv }}-uv-${{ inputs.zulip_ref }}-
          ${{ inputs.cache_epoch_uv }}-uv-

    - name: Restore emoji cache
      uses: actions/cache@v4
      with:
        path: ${{ env.EMOJI_CACHE_DIR }}
        key: ${{ inputs.cache_epoch_emoji }}-emoji-${{ inputs.zulip_ref }}-${{ hashFiles('zulip/tools/setup/emoji/emoji_map.json', 'zulip/tools/setup/emoji/build_emoji', 'zulip/tools/setup/emoji/emoji_setup_utils.py', 'zulip/tools/setup/emoji/emoji_names.py', 'zulip/package.json') }}
        restore-keys: |
          ${{ inputs.cache_epoch_emoji }}-emoji-${{ inputs.zulip_ref }}-
          ${{ inputs.cache_epoch_emoji }}-emoji-

    - name: Provision
      shell: bash
      working-directory: zulip
      env:
        PNPM_STORE_PATH: ${{ env.PNPM_STORE_PATH }}
      run: |
        set -euxo pipefail
        # Ensure pnpm uses the cached store path
        export PNPM_STORE_PATH="${PNPM_STORE_PATH}"
        ./tools/provision

    - name: Start Zulip
      shell: bash
      working-directory: zulip
      run: |
        set -euxo pipefail
        source ./tools/ci/activate-venv
        nohup ./tools/run-dev >"${ZULIP_DEV_LOG}" 2>&1 &
        echo $! > "${ZULIP_RUN_PID}"

    - name: Wait for Zulip to be ready
      shell: bash
      run: |
        set -euo pipefail
        echo "Waiting for Zulip at ${ZULIP_URL}"
        deadline=$(( $(date +%s) + ${{ inputs.wait_timeout }} ))
        until curl --get --silent --fail "${ZULIP_URL}/api/v1/server_settings" >/dev/null; do
          if [ "$(date +%s)" -gt "$deadline" ]; then
            echo "Zulip did not become ready within timeout." >&2
            exit 1
          fi
          sleep 2
        done
        echo "Zulip is up."

    - name: Export outputs
      id: outputs-step
      shell: bash
      run: |
        echo "site_url=${ZULIP_URL}" >> "$GITHUB_OUTPUT"
        echo "log_path=${ZULIP_DEV_LOG}" >> "$GITHUB_OUTPUT"

    - name: Upload Zulip log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: zulip-log-${{ inputs.zulip_ref }}
        path: ${{ env.ZULIP_DEV_LOG }}
        if-no-files-found: ignore
        retention-days: 7

    - name: Show log on failure
      if: failure()
      shell: bash
      run: |
        echo "===== zulip-dev.log ====="
        tail -n +1 "${ZULIP_DEV_LOG}" || true

    - name: Stop Zulip
      if: always()
      shell: bash
      run: |
        if [ -f "${ZULIP_RUN_PID}" ]; then
          kill "$(cat "${ZULIP_RUN_PID}")" || true
        fi
        pkill -f "tools/run-dev" || true
