/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AddAlertWords200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddAlertWords200Response{}

// AddAlertWords200Response struct for AddAlertWords200Response
type AddAlertWords200Response struct {
	Result string `json:"result"`
	Msg    string `json:"msg"`
	// An array of any parameters sent in the request that are not supported by the endpoint.  See [error handling](zulip.com/api/rest-error-handling#ignored-parameters documentation for details on this and its change history.
	IgnoredParametersUnsupported []string `json:"ignored_parameters_unsupported,omitempty"`
	// An array of strings, where each string is an alert word (or phrase) configured by the user.
	AlertWords []string `json:"alert_words,omitempty"`
}

type _AddAlertWords200Response AddAlertWords200Response

// NewAddAlertWords200Response instantiates a new AddAlertWords200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddAlertWords200Response(result string, msg string) *AddAlertWords200Response {
	this := AddAlertWords200Response{}
	this.Result = result
	this.Msg = msg
	return &this
}

// NewAddAlertWords200ResponseWithDefaults instantiates a new AddAlertWords200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddAlertWords200ResponseWithDefaults() *AddAlertWords200Response {
	this := AddAlertWords200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *AddAlertWords200Response) GetResult() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *AddAlertWords200Response) GetResultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *AddAlertWords200Response) SetResult(v string) {
	o.Result = v
}

// GetMsg returns the Msg field value
func (o *AddAlertWords200Response) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *AddAlertWords200Response) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *AddAlertWords200Response) SetMsg(v string) {
	o.Msg = v
}

// GetIgnoredParametersUnsupported returns the IgnoredParametersUnsupported field value if set, zero value otherwise.
func (o *AddAlertWords200Response) GetIgnoredParametersUnsupported() []string {
	if o == nil || IsNil(o.IgnoredParametersUnsupported) {
		var ret []string
		return ret
	}
	return o.IgnoredParametersUnsupported
}

// GetIgnoredParametersUnsupportedOk returns a tuple with the IgnoredParametersUnsupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAlertWords200Response) GetIgnoredParametersUnsupportedOk() ([]string, bool) {
	if o == nil || IsNil(o.IgnoredParametersUnsupported) {
		return nil, false
	}
	return o.IgnoredParametersUnsupported, true
}

// HasIgnoredParametersUnsupported returns a boolean if a field has been set.
func (o *AddAlertWords200Response) HasIgnoredParametersUnsupported() bool {
	if o != nil && !IsNil(o.IgnoredParametersUnsupported) {
		return true
	}

	return false
}

// SetIgnoredParametersUnsupported gets a reference to the given []string and assigns it to the IgnoredParametersUnsupported field.
func (o *AddAlertWords200Response) SetIgnoredParametersUnsupported(v []string) {
	o.IgnoredParametersUnsupported = v
}

// GetAlertWords returns the AlertWords field value if set, zero value otherwise.
func (o *AddAlertWords200Response) GetAlertWords() []string {
	if o == nil || IsNil(o.AlertWords) {
		var ret []string
		return ret
	}
	return o.AlertWords
}

// GetAlertWordsOk returns a tuple with the AlertWords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddAlertWords200Response) GetAlertWordsOk() ([]string, bool) {
	if o == nil || IsNil(o.AlertWords) {
		return nil, false
	}
	return o.AlertWords, true
}

// HasAlertWords returns a boolean if a field has been set.
func (o *AddAlertWords200Response) HasAlertWords() bool {
	if o != nil && !IsNil(o.AlertWords) {
		return true
	}

	return false
}

// SetAlertWords gets a reference to the given []string and assigns it to the AlertWords field.
func (o *AddAlertWords200Response) SetAlertWords(v []string) {
	o.AlertWords = v
}

func (o AddAlertWords200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddAlertWords200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	toSerialize["msg"] = o.Msg
	if !IsNil(o.IgnoredParametersUnsupported) {
		toSerialize["ignored_parameters_unsupported"] = o.IgnoredParametersUnsupported
	}
	if !IsNil(o.AlertWords) {
		toSerialize["alert_words"] = o.AlertWords
	}
	return toSerialize, nil
}

func (o *AddAlertWords200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
		"msg",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddAlertWords200Response := _AddAlertWords200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddAlertWords200Response)

	if err != nil {
		return err
	}

	*o = AddAlertWords200Response(varAddAlertWords200Response)

	return err
}

type NullableAddAlertWords200Response struct {
	value *AddAlertWords200Response
	isSet bool
}

func (v NullableAddAlertWords200Response) Get() *AddAlertWords200Response {
	return v.value
}

func (v *NullableAddAlertWords200Response) Set(val *AddAlertWords200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAddAlertWords200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAddAlertWords200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddAlertWords200Response(val *AddAlertWords200Response) *NullableAddAlertWords200Response {
	return &NullableAddAlertWords200Response{value: val, isSet: true}
}

func (v NullableAddAlertWords200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddAlertWords200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
