/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the ChannelFolderAddEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelFolderAddEvent{}

// ChannelFolderAddEvent Event sent to users in an organization when a channel folder is created.  **Changes**: New in Zulip 11.0 (feature level 389).
type ChannelFolderAddEvent struct {
	// The ID of the event. Events appear in increasing order but may not be consecutive.
	Id            *int32         `json:"id,omitempty"`
	Type          *string        `json:"type,omitempty"`
	Op            *string        `json:"op,omitempty"`
	ChannelFolder *ChannelFolder `json:"channel_folder,omitempty"`
}

// NewSubscriptionPeerAddEvent3 instantiates a new ChannelFolderAddEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionPeerAddEvent3() *ChannelFolderAddEvent {
	this := ChannelFolderAddEvent{}
	return &this
}

// NewSubscriptionPeerAddEvent3WithDefaults instantiates a new ChannelFolderAddEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionPeerAddEvent3WithDefaults() *ChannelFolderAddEvent {
	this := ChannelFolderAddEvent{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ChannelFolderAddEvent) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelFolderAddEvent) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ChannelFolderAddEvent) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ChannelFolderAddEvent) SetId(v int32) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ChannelFolderAddEvent) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelFolderAddEvent) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ChannelFolderAddEvent) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ChannelFolderAddEvent) SetType(v string) {
	o.Type = &v
}

// GetOp returns the Op field value if set, zero value otherwise.
func (o *ChannelFolderAddEvent) GetOp() string {
	if o == nil || IsNil(o.Op) {
		var ret string
		return ret
	}
	return *o.Op
}

// GetOpOk returns a tuple with the Op field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelFolderAddEvent) GetOpOk() (*string, bool) {
	if o == nil || IsNil(o.Op) {
		return nil, false
	}
	return o.Op, true
}

// HasOp returns a boolean if a field has been set.
func (o *ChannelFolderAddEvent) HasOp() bool {
	if o != nil && !IsNil(o.Op) {
		return true
	}

	return false
}

// SetOp gets a reference to the given string and assigns it to the Op field.
func (o *ChannelFolderAddEvent) SetOp(v string) {
	o.Op = &v
}

// GetChannelFolder returns the ChannelFolder field value if set, zero value otherwise.
func (o *ChannelFolderAddEvent) GetChannelFolder() ChannelFolder {
	if o == nil || IsNil(o.ChannelFolder) {
		var ret ChannelFolder
		return ret
	}
	return *o.ChannelFolder
}

// GetChannelFolderOk returns a tuple with the ChannelFolder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelFolderAddEvent) GetChannelFolderOk() (*ChannelFolder, bool) {
	if o == nil || IsNil(o.ChannelFolder) {
		return nil, false
	}
	return o.ChannelFolder, true
}

// HasChannelFolder returns a boolean if a field has been set.
func (o *ChannelFolderAddEvent) HasChannelFolder() bool {
	if o != nil && !IsNil(o.ChannelFolder) {
		return true
	}

	return false
}

// SetChannelFolder gets a reference to the given ChannelFolder and assigns it to the ChannelFolder field.
func (o *ChannelFolderAddEvent) SetChannelFolder(v ChannelFolder) {
	o.ChannelFolder = &v
}

func (o ChannelFolderAddEvent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelFolderAddEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Op) {
		toSerialize["op"] = o.Op
	}
	if !IsNil(o.ChannelFolder) {
		toSerialize["channel_folder"] = o.ChannelFolder
	}
	return toSerialize, nil
}

type NullableSubscriptionPeerAddEvent3 struct {
	value *ChannelFolderAddEvent
	isSet bool
}

func (v NullableSubscriptionPeerAddEvent3) Get() *ChannelFolderAddEvent {
	return v.value
}

func (v *NullableSubscriptionPeerAddEvent3) Set(val *ChannelFolderAddEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionPeerAddEvent3) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionPeerAddEvent3) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionPeerAddEvent3(val *ChannelFolderAddEvent) *NullableSubscriptionPeerAddEvent3 {
	return &NullableSubscriptionPeerAddEvent3{value: val, isSet: true}
}

func (v NullableSubscriptionPeerAddEvent3) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionPeerAddEvent3) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
