/*
Zulip REST API

Powerful open source group chat 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the ChannelCanAddSubscribersGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelCanAddSubscribersGroup{}

// ChannelCanAddSubscribersGroup A [group-setting value][setting-values] defining the set of users who have permission to add subscribers to this channel.  Users who can administer the channel or have similar realm-level permissions can add subscribers to a public channel regardless of the value of this setting.  Users in this group need not be subscribed to a private channel to add subscribers to it.  Note that a user must [have content access](/help/channel-permissions) to a channel and permission to administer the channel in order to modify this setting.  **Changes**: New in Zulip 10.0 (feature level 342). Previously, there was no channel-level setting for this permission.  [setting-values]: /api/group-setting-values 
type ChannelCanAddSubscribersGroup struct {
	// The list of IDs of individual users in the collection of users with this permission.  **Changes**: Prior to Zulip 10.0 (feature level 303), this list would include deactivated users who had the permission before being deactivated. 
	DirectMembers []int32 `json:"direct_members,omitempty"`
	// The list of IDs of the groups in the collection of users with this permission. 
	DirectSubgroups []int32 `json:"direct_subgroups,omitempty"`
}

// NewChannelCanAddSubscribersGroup instantiates a new ChannelCanAddSubscribersGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelCanAddSubscribersGroup() *ChannelCanAddSubscribersGroup {
	this := ChannelCanAddSubscribersGroup{}
	return &this
}

// NewChannelCanAddSubscribersGroupWithDefaults instantiates a new ChannelCanAddSubscribersGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelCanAddSubscribersGroupWithDefaults() *ChannelCanAddSubscribersGroup {
	this := ChannelCanAddSubscribersGroup{}
	return &this
}

// GetDirectMembers returns the DirectMembers field value if set, zero value otherwise.
func (o *ChannelCanAddSubscribersGroup) GetDirectMembers() []int32 {
	if o == nil || IsNil(o.DirectMembers) {
		var ret []int32
		return ret
	}
	return o.DirectMembers
}

// GetDirectMembersOk returns a tuple with the DirectMembers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelCanAddSubscribersGroup) GetDirectMembersOk() ([]int32, bool) {
	if o == nil || IsNil(o.DirectMembers) {
		return nil, false
	}
	return o.DirectMembers, true
}

// HasDirectMembers returns a boolean if a field has been set.
func (o *ChannelCanAddSubscribersGroup) HasDirectMembers() bool {
	if o != nil && !IsNil(o.DirectMembers) {
		return true
	}

	return false
}

// SetDirectMembers gets a reference to the given []int32 and assigns it to the DirectMembers field.
func (o *ChannelCanAddSubscribersGroup) SetDirectMembers(v []int32) {
	o.DirectMembers = v
}

// GetDirectSubgroups returns the DirectSubgroups field value if set, zero value otherwise.
func (o *ChannelCanAddSubscribersGroup) GetDirectSubgroups() []int32 {
	if o == nil || IsNil(o.DirectSubgroups) {
		var ret []int32
		return ret
	}
	return o.DirectSubgroups
}

// GetDirectSubgroupsOk returns a tuple with the DirectSubgroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelCanAddSubscribersGroup) GetDirectSubgroupsOk() ([]int32, bool) {
	if o == nil || IsNil(o.DirectSubgroups) {
		return nil, false
	}
	return o.DirectSubgroups, true
}

// HasDirectSubgroups returns a boolean if a field has been set.
func (o *ChannelCanAddSubscribersGroup) HasDirectSubgroups() bool {
	if o != nil && !IsNil(o.DirectSubgroups) {
		return true
	}

	return false
}

// SetDirectSubgroups gets a reference to the given []int32 and assigns it to the DirectSubgroups field.
func (o *ChannelCanAddSubscribersGroup) SetDirectSubgroups(v []int32) {
	o.DirectSubgroups = v
}

func (o ChannelCanAddSubscribersGroup) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelCanAddSubscribersGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DirectMembers) {
		toSerialize["direct_members"] = o.DirectMembers
	}
	if !IsNil(o.DirectSubgroups) {
		toSerialize["direct_subgroups"] = o.DirectSubgroups
	}
	return toSerialize, nil
}

type NullableChannelCanAddSubscribersGroup struct {
	value *ChannelCanAddSubscribersGroup
	isSet bool
}

func (v NullableChannelCanAddSubscribersGroup) Get() *ChannelCanAddSubscribersGroup {
	return v.value
}

func (v *NullableChannelCanAddSubscribersGroup) Set(val *ChannelCanAddSubscribersGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelCanAddSubscribersGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelCanAddSubscribersGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelCanAddSubscribersGroup(val *ChannelCanAddSubscribersGroup) *NullableChannelCanAddSubscribersGroup {
	return &NullableChannelCanAddSubscribersGroup{value: val, isSet: true}
}

func (v NullableChannelCanAddSubscribersGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelCanAddSubscribersGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


