/*
Zulip REST API

Powerful open source group chat 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CodedError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CodedError{}

// CodedError struct for CodedError
type CodedError struct {
	Result interface{} `json:"result"`
	Msg interface{} `json:"msg"`
	Code interface{} `json:"code"`
}

type _CodedError CodedError

// NewCodedError instantiates a new CodedError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCodedError(result interface{}, msg interface{}, code interface{}) *CodedError {
	this := CodedError{}
	this.Result = result
	this.Msg = msg
	this.Code = code
	return &this
}

// NewCodedErrorWithDefaults instantiates a new CodedError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCodedErrorWithDefaults() *CodedError {
	this := CodedError{}
	return &this
}

// GetResult returns the Result field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *CodedError) GetResult() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodedError) GetResultOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *CodedError) SetResult(v interface{}) {
	o.Result = v
}

// GetMsg returns the Msg field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *CodedError) GetMsg() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodedError) GetMsgOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *CodedError) SetMsg(v interface{}) {
	o.Msg = v
}

// GetCode returns the Code field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *CodedError) GetCode() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CodedError) GetCodeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *CodedError) SetCode(v interface{}) {
	o.Code = v
}

func (o CodedError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CodedError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	if o.Msg != nil {
		toSerialize["msg"] = o.Msg
	}
	if o.Code != nil {
		toSerialize["code"] = o.Code
	}
	return toSerialize, nil
}

func (o *CodedError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
		"msg",
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCodedError := _CodedError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCodedError)

	if err != nil {
		return err
	}

	*o = CodedError(varCodedError)

	return err
}

type NullableCodedError struct {
	value *CodedError
	isSet bool
}

func (v NullableCodedError) Get() *CodedError {
	return v.value
}

func (v *NullableCodedError) Set(val *CodedError) {
	v.value = val
	v.isSet = true
}

func (v NullableCodedError) IsSet() bool {
	return v.isSet
}

func (v *NullableCodedError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCodedError(val *CodedError) *NullableCodedError {
	return &NullableCodedError{value: val, isSet: true}
}

func (v NullableCodedError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCodedError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


