/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType{}

// GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType struct for GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType
type GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType struct {
}

// NewGetEvents200ResponseAllOfEventsInnerOneOf19AllOfType instantiates a new GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEvents200ResponseAllOfEventsInnerOneOf19AllOfType() *GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType {
	this := GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType{}
	return &this
}

// NewGetEvents200ResponseAllOfEventsInnerOneOf19AllOfTypeWithDefaults instantiates a new GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEvents200ResponseAllOfEventsInnerOneOf19AllOfTypeWithDefaults() *GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType {
	this := GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType{}
	return &this
}

func (o GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableGetEvents200ResponseAllOfEventsInnerOneOf19AllOfType struct {
	value *GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType
	isSet bool
}

func (v NullableGetEvents200ResponseAllOfEventsInnerOneOf19AllOfType) Get() *GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType {
	return v.value
}

func (v *NullableGetEvents200ResponseAllOfEventsInnerOneOf19AllOfType) Set(val *GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEvents200ResponseAllOfEventsInnerOneOf19AllOfType) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEvents200ResponseAllOfEventsInnerOneOf19AllOfType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEvents200ResponseAllOfEventsInnerOneOf19AllOfType(val *GetEvents200ResponseAllOfEventsInnerOneOf19AllOfType) *NullableGetEvents200ResponseAllOfEventsInnerOneOf19AllOfType {
	return &NullableGetEvents200ResponseAllOfEventsInnerOneOf19AllOfType{value: val, isSet: true}
}

func (v NullableGetEvents200ResponseAllOfEventsInnerOneOf19AllOfType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEvents200ResponseAllOfEventsInnerOneOf19AllOfType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
