/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetChannelFolders200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetChannelFolders200Response{}

// GetChannelFolders200Response struct for GetChannelFolders200Response
type GetChannelFolders200Response struct {
	Result string `json:"result"`
	Msg    string `json:"msg"`
	// An array of any parameters sent in the request that are not supported by the endpoint.  See [error handling](/api/rest-error-handling#ignored-parameters) documentation for details on this and its change history.
	IgnoredParametersUnsupported []string `json:"ignored_parameters_unsupported,omitempty"`
	// A list of channel folder objects.
	ChannelFolders []ChannelFolder `json:"channel_folders,omitempty"`
}

type _GetChannelFolders200Response GetChannelFolders200Response

// NewGetChannelFolders200Response instantiates a new GetChannelFolders200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetChannelFolders200Response(result string, msg string) *GetChannelFolders200Response {
	this := GetChannelFolders200Response{}
	this.Result = result
	this.Msg = msg
	return &this
}

// NewGetChannelFolders200ResponseWithDefaults instantiates a new GetChannelFolders200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetChannelFolders200ResponseWithDefaults() *GetChannelFolders200Response {
	this := GetChannelFolders200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *GetChannelFolders200Response) GetResult() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *GetChannelFolders200Response) GetResultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *GetChannelFolders200Response) SetResult(v string) {
	o.Result = v
}

// GetMsg returns the Msg field value
func (o *GetChannelFolders200Response) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *GetChannelFolders200Response) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *GetChannelFolders200Response) SetMsg(v string) {
	o.Msg = v
}

// GetIgnoredParametersUnsupported returns the IgnoredParametersUnsupported field value if set, zero value otherwise.
func (o *GetChannelFolders200Response) GetIgnoredParametersUnsupported() []string {
	if o == nil || IsNil(o.IgnoredParametersUnsupported) {
		var ret []string
		return ret
	}
	return o.IgnoredParametersUnsupported
}

// GetIgnoredParametersUnsupportedOk returns a tuple with the IgnoredParametersUnsupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChannelFolders200Response) GetIgnoredParametersUnsupportedOk() ([]string, bool) {
	if o == nil || IsNil(o.IgnoredParametersUnsupported) {
		return nil, false
	}
	return o.IgnoredParametersUnsupported, true
}

// HasIgnoredParametersUnsupported returns a boolean if a field has been set.
func (o *GetChannelFolders200Response) HasIgnoredParametersUnsupported() bool {
	if o != nil && !IsNil(o.IgnoredParametersUnsupported) {
		return true
	}

	return false
}

// SetIgnoredParametersUnsupported gets a reference to the given []string and assigns it to the IgnoredParametersUnsupported field.
func (o *GetChannelFolders200Response) SetIgnoredParametersUnsupported(v []string) {
	o.IgnoredParametersUnsupported = v
}

// GetChannelFolders returns the ChannelFolders field value if set, zero value otherwise.
func (o *GetChannelFolders200Response) GetChannelFolders() []ChannelFolder {
	if o == nil || IsNil(o.ChannelFolders) {
		var ret []ChannelFolder
		return ret
	}
	return o.ChannelFolders
}

// GetChannelFoldersOk returns a tuple with the ChannelFolders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetChannelFolders200Response) GetChannelFoldersOk() ([]ChannelFolder, bool) {
	if o == nil || IsNil(o.ChannelFolders) {
		return nil, false
	}
	return o.ChannelFolders, true
}

// HasChannelFolders returns a boolean if a field has been set.
func (o *GetChannelFolders200Response) HasChannelFolders() bool {
	if o != nil && !IsNil(o.ChannelFolders) {
		return true
	}

	return false
}

// SetChannelFolders gets a reference to the given []ChannelFolder and assigns it to the ChannelFolders field.
func (o *GetChannelFolders200Response) SetChannelFolders(v []ChannelFolder) {
	o.ChannelFolders = v
}

func (o GetChannelFolders200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetChannelFolders200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	toSerialize["msg"] = o.Msg
	if !IsNil(o.IgnoredParametersUnsupported) {
		toSerialize["ignored_parameters_unsupported"] = o.IgnoredParametersUnsupported
	}
	if !IsNil(o.ChannelFolders) {
		toSerialize["channel_folders"] = o.ChannelFolders
	}
	return toSerialize, nil
}

func (o *GetChannelFolders200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
		"msg",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetChannelFolders200Response := _GetChannelFolders200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetChannelFolders200Response)

	if err != nil {
		return err
	}

	*o = GetChannelFolders200Response(varGetChannelFolders200Response)

	return err
}

type NullableGetChannelFolders200Response struct {
	value *GetChannelFolders200Response
	isSet bool
}

func (v NullableGetChannelFolders200Response) Get() *GetChannelFolders200Response {
	return v.value
}

func (v *NullableGetChannelFolders200Response) Set(val *GetChannelFolders200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetChannelFolders200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetChannelFolders200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetChannelFolders200Response(val *GetChannelFolders200Response) *NullableGetChannelFolders200Response {
	return &NullableGetChannelFolders200Response{value: val, isSet: true}
}

func (v NullableGetChannelFolders200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetChannelFolders200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
