/*
Zulip REST API

Powerful open source group chat 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the GetMessage200ResponseAllOfMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMessage200ResponseAllOfMessage{}

// GetMessage200ResponseAllOfMessage An object containing details of the message.  **Changes**: New in Zulip 5.0 (feature level 120). 
type GetMessage200ResponseAllOfMessage struct {
	AvatarUrl interface{} `json:"avatar_url,omitempty"`
	Client interface{} `json:"client,omitempty"`
	Content interface{} `json:"content,omitempty"`
	ContentType interface{} `json:"content_type,omitempty"`
	DisplayRecipient interface{} `json:"display_recipient,omitempty"`
	EditHistory interface{} `json:"edit_history,omitempty"`
	Id interface{} `json:"id,omitempty"`
	IsMeMessage interface{} `json:"is_me_message,omitempty"`
	LastEditTimestamp interface{} `json:"last_edit_timestamp,omitempty"`
	LastMovedTimestamp interface{} `json:"last_moved_timestamp,omitempty"`
	Reactions interface{} `json:"reactions,omitempty"`
	RecipientId interface{} `json:"recipient_id,omitempty"`
	SenderEmail interface{} `json:"sender_email,omitempty"`
	SenderFullName interface{} `json:"sender_full_name,omitempty"`
	SenderId interface{} `json:"sender_id,omitempty"`
	SenderRealmStr interface{} `json:"sender_realm_str,omitempty"`
	StreamId interface{} `json:"stream_id,omitempty"`
	Subject interface{} `json:"subject,omitempty"`
	Submessages interface{} `json:"submessages,omitempty"`
	Timestamp interface{} `json:"timestamp,omitempty"`
	TopicLinks interface{} `json:"topic_links,omitempty"`
	Type interface{} `json:"type,omitempty"`
	// The user's [message flags][message-flags] for the message.  **Changes**: In Zulip 8.0 (feature level 224), the `wildcard_mentioned` flag was deprecated in favor of the `stream_wildcard_mentioned` and `topic_wildcard_mentioned` flags. The `wildcard_mentioned` flag exists for backwards compatibility with older clients and equals `stream_wildcard_mentioned || topic_wildcard_mentioned`. Clients supporting older server versions should treat this field as a previous name for the `stream_wildcard_mentioned` flag as topic wildcard mentions were not available prior to this feature level.  [message-flags]: /api/update-message-flags#available-flags 
	Flags []string `json:"flags,omitempty"`
}

// NewGetMessage200ResponseAllOfMessage instantiates a new GetMessage200ResponseAllOfMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMessage200ResponseAllOfMessage() *GetMessage200ResponseAllOfMessage {
	this := GetMessage200ResponseAllOfMessage{}
	return &this
}

// NewGetMessage200ResponseAllOfMessageWithDefaults instantiates a new GetMessage200ResponseAllOfMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMessage200ResponseAllOfMessageWithDefaults() *GetMessage200ResponseAllOfMessage {
	this := GetMessage200ResponseAllOfMessage{}
	return &this
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetAvatarUrl() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetAvatarUrlOk() (*interface{}, bool) {
	if o == nil || IsNil(o.AvatarUrl) {
		return nil, false
	}
	return &o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasAvatarUrl() bool {
	if o != nil && !IsNil(o.AvatarUrl) {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given interface{} and assigns it to the AvatarUrl field.
func (o *GetMessage200ResponseAllOfMessage) SetAvatarUrl(v interface{}) {
	o.AvatarUrl = v
}

// GetClient returns the Client field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetClient() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Client
}

// GetClientOk returns a tuple with the Client field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetClientOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Client) {
		return nil, false
	}
	return &o.Client, true
}

// HasClient returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasClient() bool {
	if o != nil && !IsNil(o.Client) {
		return true
	}

	return false
}

// SetClient gets a reference to the given interface{} and assigns it to the Client field.
func (o *GetMessage200ResponseAllOfMessage) SetClient(v interface{}) {
	o.Client = v
}

// GetContent returns the Content field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetContent() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetContentOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return &o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given interface{} and assigns it to the Content field.
func (o *GetMessage200ResponseAllOfMessage) SetContent(v interface{}) {
	o.Content = v
}

// GetContentType returns the ContentType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetContentType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetContentTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return &o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given interface{} and assigns it to the ContentType field.
func (o *GetMessage200ResponseAllOfMessage) SetContentType(v interface{}) {
	o.ContentType = v
}

// GetDisplayRecipient returns the DisplayRecipient field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetDisplayRecipient() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.DisplayRecipient
}

// GetDisplayRecipientOk returns a tuple with the DisplayRecipient field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetDisplayRecipientOk() (*interface{}, bool) {
	if o == nil || IsNil(o.DisplayRecipient) {
		return nil, false
	}
	return &o.DisplayRecipient, true
}

// HasDisplayRecipient returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasDisplayRecipient() bool {
	if o != nil && !IsNil(o.DisplayRecipient) {
		return true
	}

	return false
}

// SetDisplayRecipient gets a reference to the given interface{} and assigns it to the DisplayRecipient field.
func (o *GetMessage200ResponseAllOfMessage) SetDisplayRecipient(v interface{}) {
	o.DisplayRecipient = v
}

// GetEditHistory returns the EditHistory field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetEditHistory() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.EditHistory
}

// GetEditHistoryOk returns a tuple with the EditHistory field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetEditHistoryOk() (*interface{}, bool) {
	if o == nil || IsNil(o.EditHistory) {
		return nil, false
	}
	return &o.EditHistory, true
}

// HasEditHistory returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasEditHistory() bool {
	if o != nil && !IsNil(o.EditHistory) {
		return true
	}

	return false
}

// SetEditHistory gets a reference to the given interface{} and assigns it to the EditHistory field.
func (o *GetMessage200ResponseAllOfMessage) SetEditHistory(v interface{}) {
	o.EditHistory = v
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return &o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given interface{} and assigns it to the Id field.
func (o *GetMessage200ResponseAllOfMessage) SetId(v interface{}) {
	o.Id = v
}

// GetIsMeMessage returns the IsMeMessage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetIsMeMessage() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.IsMeMessage
}

// GetIsMeMessageOk returns a tuple with the IsMeMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetIsMeMessageOk() (*interface{}, bool) {
	if o == nil || IsNil(o.IsMeMessage) {
		return nil, false
	}
	return &o.IsMeMessage, true
}

// HasIsMeMessage returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasIsMeMessage() bool {
	if o != nil && !IsNil(o.IsMeMessage) {
		return true
	}

	return false
}

// SetIsMeMessage gets a reference to the given interface{} and assigns it to the IsMeMessage field.
func (o *GetMessage200ResponseAllOfMessage) SetIsMeMessage(v interface{}) {
	o.IsMeMessage = v
}

// GetLastEditTimestamp returns the LastEditTimestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetLastEditTimestamp() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.LastEditTimestamp
}

// GetLastEditTimestampOk returns a tuple with the LastEditTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetLastEditTimestampOk() (*interface{}, bool) {
	if o == nil || IsNil(o.LastEditTimestamp) {
		return nil, false
	}
	return &o.LastEditTimestamp, true
}

// HasLastEditTimestamp returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasLastEditTimestamp() bool {
	if o != nil && !IsNil(o.LastEditTimestamp) {
		return true
	}

	return false
}

// SetLastEditTimestamp gets a reference to the given interface{} and assigns it to the LastEditTimestamp field.
func (o *GetMessage200ResponseAllOfMessage) SetLastEditTimestamp(v interface{}) {
	o.LastEditTimestamp = v
}

// GetLastMovedTimestamp returns the LastMovedTimestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetLastMovedTimestamp() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.LastMovedTimestamp
}

// GetLastMovedTimestampOk returns a tuple with the LastMovedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetLastMovedTimestampOk() (*interface{}, bool) {
	if o == nil || IsNil(o.LastMovedTimestamp) {
		return nil, false
	}
	return &o.LastMovedTimestamp, true
}

// HasLastMovedTimestamp returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasLastMovedTimestamp() bool {
	if o != nil && !IsNil(o.LastMovedTimestamp) {
		return true
	}

	return false
}

// SetLastMovedTimestamp gets a reference to the given interface{} and assigns it to the LastMovedTimestamp field.
func (o *GetMessage200ResponseAllOfMessage) SetLastMovedTimestamp(v interface{}) {
	o.LastMovedTimestamp = v
}

// GetReactions returns the Reactions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetReactions() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Reactions
}

// GetReactionsOk returns a tuple with the Reactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetReactionsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Reactions) {
		return nil, false
	}
	return &o.Reactions, true
}

// HasReactions returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasReactions() bool {
	if o != nil && !IsNil(o.Reactions) {
		return true
	}

	return false
}

// SetReactions gets a reference to the given interface{} and assigns it to the Reactions field.
func (o *GetMessage200ResponseAllOfMessage) SetReactions(v interface{}) {
	o.Reactions = v
}

// GetRecipientId returns the RecipientId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetRecipientId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.RecipientId
}

// GetRecipientIdOk returns a tuple with the RecipientId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetRecipientIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.RecipientId) {
		return nil, false
	}
	return &o.RecipientId, true
}

// HasRecipientId returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasRecipientId() bool {
	if o != nil && !IsNil(o.RecipientId) {
		return true
	}

	return false
}

// SetRecipientId gets a reference to the given interface{} and assigns it to the RecipientId field.
func (o *GetMessage200ResponseAllOfMessage) SetRecipientId(v interface{}) {
	o.RecipientId = v
}

// GetSenderEmail returns the SenderEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetSenderEmail() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SenderEmail
}

// GetSenderEmailOk returns a tuple with the SenderEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetSenderEmailOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SenderEmail) {
		return nil, false
	}
	return &o.SenderEmail, true
}

// HasSenderEmail returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasSenderEmail() bool {
	if o != nil && !IsNil(o.SenderEmail) {
		return true
	}

	return false
}

// SetSenderEmail gets a reference to the given interface{} and assigns it to the SenderEmail field.
func (o *GetMessage200ResponseAllOfMessage) SetSenderEmail(v interface{}) {
	o.SenderEmail = v
}

// GetSenderFullName returns the SenderFullName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetSenderFullName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SenderFullName
}

// GetSenderFullNameOk returns a tuple with the SenderFullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetSenderFullNameOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SenderFullName) {
		return nil, false
	}
	return &o.SenderFullName, true
}

// HasSenderFullName returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasSenderFullName() bool {
	if o != nil && !IsNil(o.SenderFullName) {
		return true
	}

	return false
}

// SetSenderFullName gets a reference to the given interface{} and assigns it to the SenderFullName field.
func (o *GetMessage200ResponseAllOfMessage) SetSenderFullName(v interface{}) {
	o.SenderFullName = v
}

// GetSenderId returns the SenderId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetSenderId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SenderId
}

// GetSenderIdOk returns a tuple with the SenderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetSenderIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SenderId) {
		return nil, false
	}
	return &o.SenderId, true
}

// HasSenderId returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasSenderId() bool {
	if o != nil && !IsNil(o.SenderId) {
		return true
	}

	return false
}

// SetSenderId gets a reference to the given interface{} and assigns it to the SenderId field.
func (o *GetMessage200ResponseAllOfMessage) SetSenderId(v interface{}) {
	o.SenderId = v
}

// GetSenderRealmStr returns the SenderRealmStr field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetSenderRealmStr() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SenderRealmStr
}

// GetSenderRealmStrOk returns a tuple with the SenderRealmStr field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetSenderRealmStrOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SenderRealmStr) {
		return nil, false
	}
	return &o.SenderRealmStr, true
}

// HasSenderRealmStr returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasSenderRealmStr() bool {
	if o != nil && !IsNil(o.SenderRealmStr) {
		return true
	}

	return false
}

// SetSenderRealmStr gets a reference to the given interface{} and assigns it to the SenderRealmStr field.
func (o *GetMessage200ResponseAllOfMessage) SetSenderRealmStr(v interface{}) {
	o.SenderRealmStr = v
}

// GetStreamId returns the StreamId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetStreamId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.StreamId
}

// GetStreamIdOk returns a tuple with the StreamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetStreamIdOk() (*interface{}, bool) {
	if o == nil || IsNil(o.StreamId) {
		return nil, false
	}
	return &o.StreamId, true
}

// HasStreamId returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasStreamId() bool {
	if o != nil && !IsNil(o.StreamId) {
		return true
	}

	return false
}

// SetStreamId gets a reference to the given interface{} and assigns it to the StreamId field.
func (o *GetMessage200ResponseAllOfMessage) SetStreamId(v interface{}) {
	o.StreamId = v
}

// GetSubject returns the Subject field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetSubject() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetSubjectOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return &o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given interface{} and assigns it to the Subject field.
func (o *GetMessage200ResponseAllOfMessage) SetSubject(v interface{}) {
	o.Subject = v
}

// GetSubmessages returns the Submessages field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetSubmessages() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Submessages
}

// GetSubmessagesOk returns a tuple with the Submessages field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetSubmessagesOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Submessages) {
		return nil, false
	}
	return &o.Submessages, true
}

// HasSubmessages returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasSubmessages() bool {
	if o != nil && !IsNil(o.Submessages) {
		return true
	}

	return false
}

// SetSubmessages gets a reference to the given interface{} and assigns it to the Submessages field.
func (o *GetMessage200ResponseAllOfMessage) SetSubmessages(v interface{}) {
	o.Submessages = v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetTimestamp() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetTimestampOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return &o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given interface{} and assigns it to the Timestamp field.
func (o *GetMessage200ResponseAllOfMessage) SetTimestamp(v interface{}) {
	o.Timestamp = v
}

// GetTopicLinks returns the TopicLinks field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetTopicLinks() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.TopicLinks
}

// GetTopicLinksOk returns a tuple with the TopicLinks field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetTopicLinksOk() (*interface{}, bool) {
	if o == nil || IsNil(o.TopicLinks) {
		return nil, false
	}
	return &o.TopicLinks, true
}

// HasTopicLinks returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasTopicLinks() bool {
	if o != nil && !IsNil(o.TopicLinks) {
		return true
	}

	return false
}

// SetTopicLinks gets a reference to the given interface{} and assigns it to the TopicLinks field.
func (o *GetMessage200ResponseAllOfMessage) SetTopicLinks(v interface{}) {
	o.TopicLinks = v
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMessage200ResponseAllOfMessage) GetType() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMessage200ResponseAllOfMessage) GetTypeOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return &o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given interface{} and assigns it to the Type field.
func (o *GetMessage200ResponseAllOfMessage) SetType(v interface{}) {
	o.Type = v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *GetMessage200ResponseAllOfMessage) GetFlags() []string {
	if o == nil || IsNil(o.Flags) {
		var ret []string
		return ret
	}
	return o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMessage200ResponseAllOfMessage) GetFlagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *GetMessage200ResponseAllOfMessage) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given []string and assigns it to the Flags field.
func (o *GetMessage200ResponseAllOfMessage) SetFlags(v []string) {
	o.Flags = v
}

func (o GetMessage200ResponseAllOfMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMessage200ResponseAllOfMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.AvatarUrl != nil {
		toSerialize["avatar_url"] = o.AvatarUrl
	}
	if o.Client != nil {
		toSerialize["client"] = o.Client
	}
	if o.Content != nil {
		toSerialize["content"] = o.Content
	}
	if o.ContentType != nil {
		toSerialize["content_type"] = o.ContentType
	}
	if o.DisplayRecipient != nil {
		toSerialize["display_recipient"] = o.DisplayRecipient
	}
	if o.EditHistory != nil {
		toSerialize["edit_history"] = o.EditHistory
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.IsMeMessage != nil {
		toSerialize["is_me_message"] = o.IsMeMessage
	}
	if o.LastEditTimestamp != nil {
		toSerialize["last_edit_timestamp"] = o.LastEditTimestamp
	}
	if o.LastMovedTimestamp != nil {
		toSerialize["last_moved_timestamp"] = o.LastMovedTimestamp
	}
	if o.Reactions != nil {
		toSerialize["reactions"] = o.Reactions
	}
	if o.RecipientId != nil {
		toSerialize["recipient_id"] = o.RecipientId
	}
	if o.SenderEmail != nil {
		toSerialize["sender_email"] = o.SenderEmail
	}
	if o.SenderFullName != nil {
		toSerialize["sender_full_name"] = o.SenderFullName
	}
	if o.SenderId != nil {
		toSerialize["sender_id"] = o.SenderId
	}
	if o.SenderRealmStr != nil {
		toSerialize["sender_realm_str"] = o.SenderRealmStr
	}
	if o.StreamId != nil {
		toSerialize["stream_id"] = o.StreamId
	}
	if o.Subject != nil {
		toSerialize["subject"] = o.Subject
	}
	if o.Submessages != nil {
		toSerialize["submessages"] = o.Submessages
	}
	if o.Timestamp != nil {
		toSerialize["timestamp"] = o.Timestamp
	}
	if o.TopicLinks != nil {
		toSerialize["topic_links"] = o.TopicLinks
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	return toSerialize, nil
}

type NullableGetMessage200ResponseAllOfMessage struct {
	value *GetMessage200ResponseAllOfMessage
	isSet bool
}

func (v NullableGetMessage200ResponseAllOfMessage) Get() *GetMessage200ResponseAllOfMessage {
	return v.value
}

func (v *NullableGetMessage200ResponseAllOfMessage) Set(val *GetMessage200ResponseAllOfMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMessage200ResponseAllOfMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMessage200ResponseAllOfMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMessage200ResponseAllOfMessage(val *GetMessage200ResponseAllOfMessage) *NullableGetMessage200ResponseAllOfMessage {
	return &NullableGetMessage200ResponseAllOfMessage{value: val, isSet: true}
}

func (v NullableGetMessage200ResponseAllOfMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMessage200ResponseAllOfMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


