/*
Zulip REST API

Powerful open source group chat 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the GetEvents200ResponseAllOfEventsInnerOneOf23 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEvents200ResponseAllOfEventsInnerOneOf23{}

// GetEvents200ResponseAllOfEventsInnerOneOf23 Event sent to a user's clients when the user deletes a file they had uploaded. Useful primarily for UI showing all the files the current user has uploaded. 
type GetEvents200ResponseAllOfEventsInnerOneOf23 struct {
	// The ID of the event. Events appear in increasing order but may not be consecutive. 
	Id *int32 `json:"id,omitempty"`
	Type *string `json:"type,omitempty"`
	Op *string `json:"op,omitempty"`
	Attachment *GetEvents200ResponseAllOfEventsInnerOneOf23Attachment `json:"attachment,omitempty"`
	// The total size of all files uploaded by in the organization, in bytes. 
	UploadSpaceUsed *int32 `json:"upload_space_used,omitempty"`
}

// NewGetEvents200ResponseAllOfEventsInnerOneOf23 instantiates a new GetEvents200ResponseAllOfEventsInnerOneOf23 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEvents200ResponseAllOfEventsInnerOneOf23() *GetEvents200ResponseAllOfEventsInnerOneOf23 {
	this := GetEvents200ResponseAllOfEventsInnerOneOf23{}
	return &this
}

// NewGetEvents200ResponseAllOfEventsInnerOneOf23WithDefaults instantiates a new GetEvents200ResponseAllOfEventsInnerOneOf23 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEvents200ResponseAllOfEventsInnerOneOf23WithDefaults() *GetEvents200ResponseAllOfEventsInnerOneOf23 {
	this := GetEvents200ResponseAllOfEventsInnerOneOf23{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) SetId(v int32) {
	o.Id = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) SetType(v string) {
	o.Type = &v
}

// GetOp returns the Op field value if set, zero value otherwise.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) GetOp() string {
	if o == nil || IsNil(o.Op) {
		var ret string
		return ret
	}
	return *o.Op
}

// GetOpOk returns a tuple with the Op field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) GetOpOk() (*string, bool) {
	if o == nil || IsNil(o.Op) {
		return nil, false
	}
	return o.Op, true
}

// HasOp returns a boolean if a field has been set.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) HasOp() bool {
	if o != nil && !IsNil(o.Op) {
		return true
	}

	return false
}

// SetOp gets a reference to the given string and assigns it to the Op field.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) SetOp(v string) {
	o.Op = &v
}

// GetAttachment returns the Attachment field value if set, zero value otherwise.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) GetAttachment() GetEvents200ResponseAllOfEventsInnerOneOf23Attachment {
	if o == nil || IsNil(o.Attachment) {
		var ret GetEvents200ResponseAllOfEventsInnerOneOf23Attachment
		return ret
	}
	return *o.Attachment
}

// GetAttachmentOk returns a tuple with the Attachment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) GetAttachmentOk() (*GetEvents200ResponseAllOfEventsInnerOneOf23Attachment, bool) {
	if o == nil || IsNil(o.Attachment) {
		return nil, false
	}
	return o.Attachment, true
}

// HasAttachment returns a boolean if a field has been set.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) HasAttachment() bool {
	if o != nil && !IsNil(o.Attachment) {
		return true
	}

	return false
}

// SetAttachment gets a reference to the given GetEvents200ResponseAllOfEventsInnerOneOf23Attachment and assigns it to the Attachment field.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) SetAttachment(v GetEvents200ResponseAllOfEventsInnerOneOf23Attachment) {
	o.Attachment = &v
}

// GetUploadSpaceUsed returns the UploadSpaceUsed field value if set, zero value otherwise.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) GetUploadSpaceUsed() int32 {
	if o == nil || IsNil(o.UploadSpaceUsed) {
		var ret int32
		return ret
	}
	return *o.UploadSpaceUsed
}

// GetUploadSpaceUsedOk returns a tuple with the UploadSpaceUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) GetUploadSpaceUsedOk() (*int32, bool) {
	if o == nil || IsNil(o.UploadSpaceUsed) {
		return nil, false
	}
	return o.UploadSpaceUsed, true
}

// HasUploadSpaceUsed returns a boolean if a field has been set.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) HasUploadSpaceUsed() bool {
	if o != nil && !IsNil(o.UploadSpaceUsed) {
		return true
	}

	return false
}

// SetUploadSpaceUsed gets a reference to the given int32 and assigns it to the UploadSpaceUsed field.
func (o *GetEvents200ResponseAllOfEventsInnerOneOf23) SetUploadSpaceUsed(v int32) {
	o.UploadSpaceUsed = &v
}

func (o GetEvents200ResponseAllOfEventsInnerOneOf23) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEvents200ResponseAllOfEventsInnerOneOf23) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Op) {
		toSerialize["op"] = o.Op
	}
	if !IsNil(o.Attachment) {
		toSerialize["attachment"] = o.Attachment
	}
	if !IsNil(o.UploadSpaceUsed) {
		toSerialize["upload_space_used"] = o.UploadSpaceUsed
	}
	return toSerialize, nil
}

type NullableGetEvents200ResponseAllOfEventsInnerOneOf23 struct {
	value *GetEvents200ResponseAllOfEventsInnerOneOf23
	isSet bool
}

func (v NullableGetEvents200ResponseAllOfEventsInnerOneOf23) Get() *GetEvents200ResponseAllOfEventsInnerOneOf23 {
	return v.value
}

func (v *NullableGetEvents200ResponseAllOfEventsInnerOneOf23) Set(val *GetEvents200ResponseAllOfEventsInnerOneOf23) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEvents200ResponseAllOfEventsInnerOneOf23) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEvents200ResponseAllOfEventsInnerOneOf23) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEvents200ResponseAllOfEventsInnerOneOf23(val *GetEvents200ResponseAllOfEventsInnerOneOf23) *NullableGetEvents200ResponseAllOfEventsInnerOneOf23 {
	return &NullableGetEvents200ResponseAllOfEventsInnerOneOf23{value: val, isSet: true}
}

func (v NullableGetEvents200ResponseAllOfEventsInnerOneOf23) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEvents200ResponseAllOfEventsInnerOneOf23) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


