/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetUserGroupSubgroups200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUserGroupSubgroups200Response{}

// GetUserGroupSubgroups200Response struct for GetUserGroupSubgroups200Response
type GetUserGroupSubgroups200Response struct {
	Result string `json:"result"`
	Msg    string `json:"msg"`
	// An array of any parameters sent in the request that are not supported by the endpoint.  See [error handling](zulip.com/api/rest-error-handling#ignored-parameters documentation for details on this and its change history.
	IgnoredParametersUnsupported []string `json:"ignored_parameters_unsupported,omitempty"`
	// A list containing the IDs of subgroups of the user group.
	Subgroups []int32 `json:"subgroups,omitempty"`
}

type _GetUserGroupSubgroups200Response GetUserGroupSubgroups200Response

// NewGetUserGroupSubgroups200Response instantiates a new GetUserGroupSubgroups200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserGroupSubgroups200Response(result string, msg string) *GetUserGroupSubgroups200Response {
	this := GetUserGroupSubgroups200Response{}
	this.Result = result
	this.Msg = msg
	return &this
}

// NewGetUserGroupSubgroups200ResponseWithDefaults instantiates a new GetUserGroupSubgroups200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserGroupSubgroups200ResponseWithDefaults() *GetUserGroupSubgroups200Response {
	this := GetUserGroupSubgroups200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *GetUserGroupSubgroups200Response) GetResult() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *GetUserGroupSubgroups200Response) GetResultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *GetUserGroupSubgroups200Response) SetResult(v string) {
	o.Result = v
}

// GetMsg returns the Msg field value
func (o *GetUserGroupSubgroups200Response) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *GetUserGroupSubgroups200Response) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *GetUserGroupSubgroups200Response) SetMsg(v string) {
	o.Msg = v
}

// GetIgnoredParametersUnsupported returns the IgnoredParametersUnsupported field value if set, zero value otherwise.
func (o *GetUserGroupSubgroups200Response) GetIgnoredParametersUnsupported() []string {
	if o == nil || IsNil(o.IgnoredParametersUnsupported) {
		var ret []string
		return ret
	}
	return o.IgnoredParametersUnsupported
}

// GetIgnoredParametersUnsupportedOk returns a tuple with the IgnoredParametersUnsupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserGroupSubgroups200Response) GetIgnoredParametersUnsupportedOk() ([]string, bool) {
	if o == nil || IsNil(o.IgnoredParametersUnsupported) {
		return nil, false
	}
	return o.IgnoredParametersUnsupported, true
}

// HasIgnoredParametersUnsupported returns a boolean if a field has been set.
func (o *GetUserGroupSubgroups200Response) HasIgnoredParametersUnsupported() bool {
	if o != nil && !IsNil(o.IgnoredParametersUnsupported) {
		return true
	}

	return false
}

// SetIgnoredParametersUnsupported gets a reference to the given []string and assigns it to the IgnoredParametersUnsupported field.
func (o *GetUserGroupSubgroups200Response) SetIgnoredParametersUnsupported(v []string) {
	o.IgnoredParametersUnsupported = v
}

// GetSubgroups returns the Subgroups field value if set, zero value otherwise.
func (o *GetUserGroupSubgroups200Response) GetSubgroups() []int32 {
	if o == nil || IsNil(o.Subgroups) {
		var ret []int32
		return ret
	}
	return o.Subgroups
}

// GetSubgroupsOk returns a tuple with the Subgroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserGroupSubgroups200Response) GetSubgroupsOk() ([]int32, bool) {
	if o == nil || IsNil(o.Subgroups) {
		return nil, false
	}
	return o.Subgroups, true
}

// HasSubgroups returns a boolean if a field has been set.
func (o *GetUserGroupSubgroups200Response) HasSubgroups() bool {
	if o != nil && !IsNil(o.Subgroups) {
		return true
	}

	return false
}

// SetSubgroups gets a reference to the given []int32 and assigns it to the Subgroups field.
func (o *GetUserGroupSubgroups200Response) SetSubgroups(v []int32) {
	o.Subgroups = v
}

func (o GetUserGroupSubgroups200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUserGroupSubgroups200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	toSerialize["msg"] = o.Msg
	if !IsNil(o.IgnoredParametersUnsupported) {
		toSerialize["ignored_parameters_unsupported"] = o.IgnoredParametersUnsupported
	}
	if !IsNil(o.Subgroups) {
		toSerialize["subgroups"] = o.Subgroups
	}
	return toSerialize, nil
}

func (o *GetUserGroupSubgroups200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
		"msg",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetUserGroupSubgroups200Response := _GetUserGroupSubgroups200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetUserGroupSubgroups200Response)

	if err != nil {
		return err
	}

	*o = GetUserGroupSubgroups200Response(varGetUserGroupSubgroups200Response)

	return err
}

type NullableGetUserGroupSubgroups200Response struct {
	value *GetUserGroupSubgroups200Response
	isSet bool
}

func (v NullableGetUserGroupSubgroups200Response) Get() *GetUserGroupSubgroups200Response {
	return v.value
}

func (v *NullableGetUserGroupSubgroups200Response) Set(val *GetUserGroupSubgroups200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserGroupSubgroups200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserGroupSubgroups200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserGroupSubgroups200Response(val *GetUserGroupSubgroups200Response) *NullableGetUserGroupSubgroups200Response {
	return &NullableGetUserGroupSubgroups200Response{value: val, isSet: true}
}

func (v NullableGetUserGroupSubgroups200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserGroupSubgroups200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
