/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// GetEvents200ResponseAllOfEventsInnerOneOf68Value - The new value of the property.
type GetEvents200ResponseAllOfEventsInnerOneOf68Value struct {
	Bool   *bool
	Int32  *int32
	String *string
}

// boolAsGetEvents200ResponseAllOfEventsInnerOneOf68Value is a convenience function that returns bool wrapped in GetEvents200ResponseAllOfEventsInnerOneOf68Value
func BoolAsGetEvents200ResponseAllOfEventsInnerOneOf68Value(v *bool) GetEvents200ResponseAllOfEventsInnerOneOf68Value {
	return GetEvents200ResponseAllOfEventsInnerOneOf68Value{
		Bool: v,
	}
}

// int32AsGetEvents200ResponseAllOfEventsInnerOneOf68Value is a convenience function that returns int32 wrapped in GetEvents200ResponseAllOfEventsInnerOneOf68Value
func Int32AsGetEvents200ResponseAllOfEventsInnerOneOf68Value(v *int32) GetEvents200ResponseAllOfEventsInnerOneOf68Value {
	return GetEvents200ResponseAllOfEventsInnerOneOf68Value{
		Int32: v,
	}
}

// stringAsGetEvents200ResponseAllOfEventsInnerOneOf68Value is a convenience function that returns string wrapped in GetEvents200ResponseAllOfEventsInnerOneOf68Value
func StringAsGetEvents200ResponseAllOfEventsInnerOneOf68Value(v *string) GetEvents200ResponseAllOfEventsInnerOneOf68Value {
	return GetEvents200ResponseAllOfEventsInnerOneOf68Value{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetEvents200ResponseAllOfEventsInnerOneOf68Value) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Bool
	err = newStrictDecoder(data).Decode(&dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			if err = validator.Validate(dst.Bool); err != nil {
				dst.Bool = nil
			} else {
				match++
			}
		}
	} else {
		dst.Bool = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			if err = validator.Validate(dst.Int32); err != nil {
				dst.Int32 = nil
			} else {
				match++
			}
		}
	} else {
		dst.Int32 = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Bool = nil
		dst.Int32 = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(GetEvents200ResponseAllOfEventsInnerOneOf68Value)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(GetEvents200ResponseAllOfEventsInnerOneOf68Value)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetEvents200ResponseAllOfEventsInnerOneOf68Value) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetEvents200ResponseAllOfEventsInnerOneOf68Value) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.Bool != nil {
		return obj.Bool
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj GetEvents200ResponseAllOfEventsInnerOneOf68Value) GetActualInstanceValue() interface{} {
	if obj.Bool != nil {
		return *obj.Bool
	}

	if obj.Int32 != nil {
		return *obj.Int32
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableGetEvents200ResponseAllOfEventsInnerOneOf68Value struct {
	value *GetEvents200ResponseAllOfEventsInnerOneOf68Value
	isSet bool
}

func (v NullableGetEvents200ResponseAllOfEventsInnerOneOf68Value) Get() *GetEvents200ResponseAllOfEventsInnerOneOf68Value {
	return v.value
}

func (v *NullableGetEvents200ResponseAllOfEventsInnerOneOf68Value) Set(val *GetEvents200ResponseAllOfEventsInnerOneOf68Value) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEvents200ResponseAllOfEventsInnerOneOf68Value) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEvents200ResponseAllOfEventsInnerOneOf68Value) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEvents200ResponseAllOfEventsInnerOneOf68Value(val *GetEvents200ResponseAllOfEventsInnerOneOf68Value) *NullableGetEvents200ResponseAllOfEventsInnerOneOf68Value {
	return &NullableGetEvents200ResponseAllOfEventsInnerOneOf68Value{value: val, isSet: true}
}

func (v NullableGetEvents200ResponseAllOfEventsInnerOneOf68Value) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEvents200ResponseAllOfEventsInnerOneOf68Value) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
