/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the GetUserGroups200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUserGroups200Response{}

// GetUserGroups200Response struct for GetUserGroups200Response
type GetUserGroups200Response struct {
	Result string `json:"result"`
	Msg    string `json:"msg"`
	// An array of any parameters sent in the request that are not supported by the endpoint.  See [error handling](/api/rest-error-handling#ignored-parameters) documentation for details on this and its change history.
	IgnoredParametersUnsupported []string `json:"ignored_parameters_unsupported,omitempty"`
	// A list of `user_group` objects.
	UserGroups []GetUserGroups200ResponseAllOfUserGroupsInner `json:"user_groups,omitempty"`
}

type _GetUserGroups200Response GetUserGroups200Response

// NewGetUserGroups200Response instantiates a new GetUserGroups200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserGroups200Response(result string, msg string) *GetUserGroups200Response {
	this := GetUserGroups200Response{}
	this.Result = result
	this.Msg = msg
	return &this
}

// NewGetUserGroups200ResponseWithDefaults instantiates a new GetUserGroups200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserGroups200ResponseWithDefaults() *GetUserGroups200Response {
	this := GetUserGroups200Response{}
	return &this
}

// GetResult returns the Result field value
func (o *GetUserGroups200Response) GetResult() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *GetUserGroups200Response) GetResultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *GetUserGroups200Response) SetResult(v string) {
	o.Result = v
}

// GetMsg returns the Msg field value
func (o *GetUserGroups200Response) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *GetUserGroups200Response) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *GetUserGroups200Response) SetMsg(v string) {
	o.Msg = v
}

// GetIgnoredParametersUnsupported returns the IgnoredParametersUnsupported field value if set, zero value otherwise.
func (o *GetUserGroups200Response) GetIgnoredParametersUnsupported() []string {
	if o == nil || IsNil(o.IgnoredParametersUnsupported) {
		var ret []string
		return ret
	}
	return o.IgnoredParametersUnsupported
}

// GetIgnoredParametersUnsupportedOk returns a tuple with the IgnoredParametersUnsupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserGroups200Response) GetIgnoredParametersUnsupportedOk() ([]string, bool) {
	if o == nil || IsNil(o.IgnoredParametersUnsupported) {
		return nil, false
	}
	return o.IgnoredParametersUnsupported, true
}

// HasIgnoredParametersUnsupported returns a boolean if a field has been set.
func (o *GetUserGroups200Response) HasIgnoredParametersUnsupported() bool {
	if o != nil && !IsNil(o.IgnoredParametersUnsupported) {
		return true
	}

	return false
}

// SetIgnoredParametersUnsupported gets a reference to the given []string and assigns it to the IgnoredParametersUnsupported field.
func (o *GetUserGroups200Response) SetIgnoredParametersUnsupported(v []string) {
	o.IgnoredParametersUnsupported = v
}

// GetUserGroups returns the UserGroups field value if set, zero value otherwise.
func (o *GetUserGroups200Response) GetUserGroups() []GetUserGroups200ResponseAllOfUserGroupsInner {
	if o == nil || IsNil(o.UserGroups) {
		var ret []GetUserGroups200ResponseAllOfUserGroupsInner
		return ret
	}
	return o.UserGroups
}

// GetUserGroupsOk returns a tuple with the UserGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserGroups200Response) GetUserGroupsOk() ([]GetUserGroups200ResponseAllOfUserGroupsInner, bool) {
	if o == nil || IsNil(o.UserGroups) {
		return nil, false
	}
	return o.UserGroups, true
}

// HasUserGroups returns a boolean if a field has been set.
func (o *GetUserGroups200Response) HasUserGroups() bool {
	if o != nil && !IsNil(o.UserGroups) {
		return true
	}

	return false
}

// SetUserGroups gets a reference to the given []GetUserGroups200ResponseAllOfUserGroupsInner and assigns it to the UserGroups field.
func (o *GetUserGroups200Response) SetUserGroups(v []GetUserGroups200ResponseAllOfUserGroupsInner) {
	o.UserGroups = v
}

func (o GetUserGroups200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUserGroups200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	toSerialize["msg"] = o.Msg
	if !IsNil(o.IgnoredParametersUnsupported) {
		toSerialize["ignored_parameters_unsupported"] = o.IgnoredParametersUnsupported
	}
	if !IsNil(o.UserGroups) {
		toSerialize["user_groups"] = o.UserGroups
	}
	return toSerialize, nil
}

func (o *GetUserGroups200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
		"msg",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetUserGroups200Response := _GetUserGroups200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetUserGroups200Response)

	if err != nil {
		return err
	}

	*o = GetUserGroups200Response(varGetUserGroups200Response)

	return err
}

type NullableGetUserGroups200Response struct {
	value *GetUserGroups200Response
	isSet bool
}

func (v NullableGetUserGroups200Response) Get() *GetUserGroups200Response {
	return v.value
}

func (v *NullableGetUserGroups200Response) Set(val *GetUserGroups200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserGroups200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserGroups200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserGroups200Response(val *GetUserGroups200Response) *NullableGetUserGroups200Response {
	return &NullableGetUserGroups200Response{value: val, isSet: true}
}

func (v NullableGetUserGroups200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserGroups200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
