/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the IncompatibleParametersError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IncompatibleParametersError{}

// IncompatibleParametersError struct for IncompatibleParametersError
type IncompatibleParametersError struct {
	Result string `json:"result"`
	Msg    string `json:"msg"`
	// A string that identifies the error.
	Code string `json:"code"`
	// A string containing the parameters, separated by commas, that are incompatible.
	Parameters *string `json:"parameters,omitempty"`
}

type _IncompatibleParametersError IncompatibleParametersError

// NewIncompatibleParametersError instantiates a new IncompatibleParametersError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIncompatibleParametersError(result string, msg string, code string) *IncompatibleParametersError {
	this := IncompatibleParametersError{}
	this.Result = result
	this.Msg = msg
	this.Code = code
	return &this
}

// NewIncompatibleParametersErrorWithDefaults instantiates a new IncompatibleParametersError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIncompatibleParametersErrorWithDefaults() *IncompatibleParametersError {
	this := IncompatibleParametersError{}
	return &this
}

// GetResult returns the Result field value
func (o *IncompatibleParametersError) GetResult() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *IncompatibleParametersError) GetResultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *IncompatibleParametersError) SetResult(v string) {
	o.Result = v
}

// GetMsg returns the Msg field value
func (o *IncompatibleParametersError) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *IncompatibleParametersError) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *IncompatibleParametersError) SetMsg(v string) {
	o.Msg = v
}

// GetCode returns the Code field value
func (o *IncompatibleParametersError) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *IncompatibleParametersError) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *IncompatibleParametersError) SetCode(v string) {
	o.Code = v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *IncompatibleParametersError) GetParameters() string {
	if o == nil || IsNil(o.Parameters) {
		var ret string
		return ret
	}
	return *o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IncompatibleParametersError) GetParametersOk() (*string, bool) {
	if o == nil || IsNil(o.Parameters) {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *IncompatibleParametersError) HasParameters() bool {
	if o != nil && !IsNil(o.Parameters) {
		return true
	}

	return false
}

// SetParameters gets a reference to the given string and assigns it to the Parameters field.
func (o *IncompatibleParametersError) SetParameters(v string) {
	o.Parameters = &v
}

func (o IncompatibleParametersError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IncompatibleParametersError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	toSerialize["msg"] = o.Msg
	toSerialize["code"] = o.Code
	if !IsNil(o.Parameters) {
		toSerialize["parameters"] = o.Parameters
	}
	return toSerialize, nil
}

func (o *IncompatibleParametersError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
		"msg",
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIncompatibleParametersError := _IncompatibleParametersError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIncompatibleParametersError)

	if err != nil {
		return err
	}

	*o = IncompatibleParametersError(varIncompatibleParametersError)

	return err
}

type NullableIncompatibleParametersError struct {
	value *IncompatibleParametersError
	isSet bool
}

func (v NullableIncompatibleParametersError) Get() *IncompatibleParametersError {
	return v.value
}

func (v *NullableIncompatibleParametersError) Set(val *IncompatibleParametersError) {
	v.value = val
	v.isSet = true
}

func (v NullableIncompatibleParametersError) IsSet() bool {
	return v.isSet
}

func (v *NullableIncompatibleParametersError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIncompatibleParametersError(val *IncompatibleParametersError) *NullableIncompatibleParametersError {
	return &NullableIncompatibleParametersError{value: val, isSet: true}
}

func (v NullableIncompatibleParametersError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIncompatibleParametersError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
