/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the InvalidPushDeviceTokenError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InvalidPushDeviceTokenError{}

// InvalidPushDeviceTokenError ## Invalid push device token  A typical failed JSON response for when the push device token is not recognized by the Zulip server:
type InvalidPushDeviceTokenError struct {
	Result string `json:"result"`
	Msg    string `json:"msg"`
	// A string that identifies the error.
	Code string `json:"code"`
}

type _InvalidPushDeviceTokenError InvalidPushDeviceTokenError

// NewInvalidPushDeviceTokenError instantiates a new InvalidPushDeviceTokenError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInvalidPushDeviceTokenError(result string, msg string, code string) *InvalidPushDeviceTokenError {
	this := InvalidPushDeviceTokenError{}
	this.Result = result
	this.Msg = msg
	this.Code = code
	return &this
}

// NewInvalidPushDeviceTokenErrorWithDefaults instantiates a new InvalidPushDeviceTokenError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInvalidPushDeviceTokenErrorWithDefaults() *InvalidPushDeviceTokenError {
	this := InvalidPushDeviceTokenError{}
	return &this
}

// GetResult returns the Result field value
func (o *InvalidPushDeviceTokenError) GetResult() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *InvalidPushDeviceTokenError) GetResultOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *InvalidPushDeviceTokenError) SetResult(v string) {
	o.Result = v
}

// GetMsg returns the Msg field value
func (o *InvalidPushDeviceTokenError) GetMsg() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
func (o *InvalidPushDeviceTokenError) GetMsgOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *InvalidPushDeviceTokenError) SetMsg(v string) {
	o.Msg = v
}

// GetCode returns the Code field value
func (o *InvalidPushDeviceTokenError) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *InvalidPushDeviceTokenError) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *InvalidPushDeviceTokenError) SetCode(v string) {
	o.Code = v
}

func (o InvalidPushDeviceTokenError) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InvalidPushDeviceTokenError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["result"] = o.Result
	toSerialize["msg"] = o.Msg
	toSerialize["code"] = o.Code
	return toSerialize, nil
}

func (o *InvalidPushDeviceTokenError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
		"msg",
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInvalidPushDeviceTokenError := _InvalidPushDeviceTokenError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInvalidPushDeviceTokenError)

	if err != nil {
		return err
	}

	*o = InvalidPushDeviceTokenError(varInvalidPushDeviceTokenError)

	return err
}

type NullableInvalidPushDeviceTokenError struct {
	value *InvalidPushDeviceTokenError
	isSet bool
}

func (v NullableInvalidPushDeviceTokenError) Get() *InvalidPushDeviceTokenError {
	return v.value
}

func (v *NullableInvalidPushDeviceTokenError) Set(val *InvalidPushDeviceTokenError) {
	v.value = val
	v.isSet = true
}

func (v NullableInvalidPushDeviceTokenError) IsSet() bool {
	return v.isSet
}

func (v *NullableInvalidPushDeviceTokenError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInvalidPushDeviceTokenError(val *InvalidPushDeviceTokenError) *NullableInvalidPushDeviceTokenError {
	return &NullableInvalidPushDeviceTokenError{value: val, isSet: true}
}

func (v NullableInvalidPushDeviceTokenError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInvalidPushDeviceTokenError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
