/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the RealmBilling type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RealmBilling{}

// RealmBilling Present if `realm_billing` is present in `fetch_event_types`.  A dictionary containing billing information of the organization.  **Changes**: New in Zulip 10.0 (feature level 363).
type RealmBilling struct {
	// Whether there is a pending sponsorship request for the organization. Note that this field will always be `false` if the user is not in `can_manage_billing_group`.  **Changes**: New in Zulip 10.0 (feature level 363).
	HasPendingSponsorshipRequest *bool `json:"has_pending_sponsorship_request,omitempty"`
}

// NewRealmBilling instantiates a new RealmBilling object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRealmBilling() *RealmBilling {
	this := RealmBilling{}
	return &this
}

// NewRealmBillingWithDefaults instantiates a new RealmBilling object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRealmBillingWithDefaults() *RealmBilling {
	this := RealmBilling{}
	return &this
}

// GetHasPendingSponsorshipRequest returns the HasPendingSponsorshipRequest field value if set, zero value otherwise.
func (o *RealmBilling) GetHasPendingSponsorshipRequest() bool {
	if o == nil || IsNil(o.HasPendingSponsorshipRequest) {
		var ret bool
		return ret
	}
	return *o.HasPendingSponsorshipRequest
}

// GetHasPendingSponsorshipRequestOk returns a tuple with the HasPendingSponsorshipRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RealmBilling) GetHasPendingSponsorshipRequestOk() (*bool, bool) {
	if o == nil || IsNil(o.HasPendingSponsorshipRequest) {
		return nil, false
	}
	return o.HasPendingSponsorshipRequest, true
}

// HasHasPendingSponsorshipRequest returns a boolean if a field has been set.
func (o *RealmBilling) HasHasPendingSponsorshipRequest() bool {
	if o != nil && !IsNil(o.HasPendingSponsorshipRequest) {
		return true
	}

	return false
}

// SetHasPendingSponsorshipRequest gets a reference to the given bool and assigns it to the HasPendingSponsorshipRequest field.
func (o *RealmBilling) SetHasPendingSponsorshipRequest(v bool) {
	o.HasPendingSponsorshipRequest = &v
}

func (o RealmBilling) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RealmBilling) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HasPendingSponsorshipRequest) {
		toSerialize["has_pending_sponsorship_request"] = o.HasPendingSponsorshipRequest
	}
	return toSerialize, nil
}

type NullableRealmBilling struct {
	value *RealmBilling
	isSet bool
}

func (v NullableRealmBilling) Get() *RealmBilling {
	return v.value
}

func (v *NullableRealmBilling) Set(val *RealmBilling) {
	v.value = val
	v.isSet = true
}

func (v NullableRealmBilling) IsSet() bool {
	return v.isSet
}

func (v *NullableRealmBilling) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRealmBilling(val *RealmBilling) *NullableRealmBilling {
	return &NullableRealmBilling{value: val, isSet: true}
}

func (v NullableRealmBilling) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRealmBilling) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
