/*
Zulip REST API

Powerful open source group chat 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner{}

// RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner Object containing details of an embedded bot. Embedded bots are an experimental feature not enabled in production yet. 
type RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner struct {
	// The name of the bot. 
	Name *string `json:"name,omitempty"`
	// A dictionary of string key/value pairs, which describe the configuration for the bot. These are usually details like API keys, and are unique to the integration/bot. Can be an empty dictionary. 
	Config *map[string]string `json:"config,omitempty"`
}

// NewRegisterQueue200ResponseAllOfRealmEmbeddedBotsInner instantiates a new RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterQueue200ResponseAllOfRealmEmbeddedBotsInner() *RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner {
	this := RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner{}
	return &this
}

// NewRegisterQueue200ResponseAllOfRealmEmbeddedBotsInnerWithDefaults instantiates a new RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterQueue200ResponseAllOfRealmEmbeddedBotsInnerWithDefaults() *RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner {
	this := RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) SetName(v string) {
	o.Name = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) GetConfig() map[string]string {
	if o == nil || IsNil(o.Config) {
		var ret map[string]string
		return ret
	}
	return *o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) GetConfigOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Config) {
		return nil, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]string and assigns it to the Config field.
func (o *RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) SetConfig(v map[string]string) {
	o.Config = &v
}

func (o RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	return toSerialize, nil
}

type NullableRegisterQueue200ResponseAllOfRealmEmbeddedBotsInner struct {
	value *RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner
	isSet bool
}

func (v NullableRegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) Get() *RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner {
	return v.value
}

func (v *NullableRegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) Set(val *RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterQueue200ResponseAllOfRealmEmbeddedBotsInner(val *RegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) *NullableRegisterQueue200ResponseAllOfRealmEmbeddedBotsInner {
	return &NullableRegisterQueue200ResponseAllOfRealmEmbeddedBotsInner{value: val, isSet: true}
}

func (v NullableRegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterQueue200ResponseAllOfRealmEmbeddedBotsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


