/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the RegisterQueue200ResponseAllOfRealmBilling type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterQueue200ResponseAllOfRealmBilling{}

// RegisterQueue200ResponseAllOfRealmBilling Present if `realm_billing` is present in `fetch_event_types`.  A dictionary containing billing information of the organization.  **Changes**: New in Zulip 10.0 (feature level 363).
type RegisterQueue200ResponseAllOfRealmBilling struct {
	// Whether there is a pending sponsorship request for the organization. Note that this field will always be `false` if the user is not in `can_manage_billing_group`.  **Changes**: New in Zulip 10.0 (feature level 363).
	HasPendingSponsorshipRequest *bool `json:"has_pending_sponsorship_request,omitempty"`
}

// NewRegisterQueue200ResponseAllOfRealmBilling instantiates a new RegisterQueue200ResponseAllOfRealmBilling object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterQueue200ResponseAllOfRealmBilling() *RegisterQueue200ResponseAllOfRealmBilling {
	this := RegisterQueue200ResponseAllOfRealmBilling{}
	return &this
}

// NewRegisterQueue200ResponseAllOfRealmBillingWithDefaults instantiates a new RegisterQueue200ResponseAllOfRealmBilling object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterQueue200ResponseAllOfRealmBillingWithDefaults() *RegisterQueue200ResponseAllOfRealmBilling {
	this := RegisterQueue200ResponseAllOfRealmBilling{}
	return &this
}

// GetHasPendingSponsorshipRequest returns the HasPendingSponsorshipRequest field value if set, zero value otherwise.
func (o *RegisterQueue200ResponseAllOfRealmBilling) GetHasPendingSponsorshipRequest() bool {
	if o == nil || IsNil(o.HasPendingSponsorshipRequest) {
		var ret bool
		return ret
	}
	return *o.HasPendingSponsorshipRequest
}

// GetHasPendingSponsorshipRequestOk returns a tuple with the HasPendingSponsorshipRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterQueue200ResponseAllOfRealmBilling) GetHasPendingSponsorshipRequestOk() (*bool, bool) {
	if o == nil || IsNil(o.HasPendingSponsorshipRequest) {
		return nil, false
	}
	return o.HasPendingSponsorshipRequest, true
}

// HasHasPendingSponsorshipRequest returns a boolean if a field has been set.
func (o *RegisterQueue200ResponseAllOfRealmBilling) HasHasPendingSponsorshipRequest() bool {
	if o != nil && !IsNil(o.HasPendingSponsorshipRequest) {
		return true
	}

	return false
}

// SetHasPendingSponsorshipRequest gets a reference to the given bool and assigns it to the HasPendingSponsorshipRequest field.
func (o *RegisterQueue200ResponseAllOfRealmBilling) SetHasPendingSponsorshipRequest(v bool) {
	o.HasPendingSponsorshipRequest = &v
}

func (o RegisterQueue200ResponseAllOfRealmBilling) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterQueue200ResponseAllOfRealmBilling) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HasPendingSponsorshipRequest) {
		toSerialize["has_pending_sponsorship_request"] = o.HasPendingSponsorshipRequest
	}
	return toSerialize, nil
}

type NullableRegisterQueue200ResponseAllOfRealmBilling struct {
	value *RegisterQueue200ResponseAllOfRealmBilling
	isSet bool
}

func (v NullableRegisterQueue200ResponseAllOfRealmBilling) Get() *RegisterQueue200ResponseAllOfRealmBilling {
	return v.value
}

func (v *NullableRegisterQueue200ResponseAllOfRealmBilling) Set(val *RegisterQueue200ResponseAllOfRealmBilling) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterQueue200ResponseAllOfRealmBilling) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterQueue200ResponseAllOfRealmBilling) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterQueue200ResponseAllOfRealmBilling(val *RegisterQueue200ResponseAllOfRealmBilling) *NullableRegisterQueue200ResponseAllOfRealmBilling {
	return &NullableRegisterQueue200ResponseAllOfRealmBilling{value: val, isSet: true}
}

func (v NullableRegisterQueue200ResponseAllOfRealmBilling) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterQueue200ResponseAllOfRealmBilling) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
