/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the ScheduledMessageBase type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScheduledMessageBase{}

// ScheduledMessageBase Object containing details of the scheduled message.
type ScheduledMessageBase struct {
	// The unique ID of the scheduled message, which can be used to modify or delete the scheduled message.  This is different from the unique ID that the message will have after it is sent.
	ScheduledMessageId int32 `json:"scheduled_message_id"`
	// The type of the scheduled message. Either `\"stream\"` or `\"private\"`.
	Type RecipientType `json:"type"`
	To   Recipients    `json:"to"`
	// Only present if `type` is `\"stream\"`.  The topic for the channel message.
	Topic *string `json:"topic,omitempty"`
	// The content/body of the scheduled message, in [Zulip-flavored Markdown](zulip.com/help/format-your-message-using-markdown format.  See [Markdown message formatting](zulip.com/api/message-formatting for details on Zulip's HTML format.
	Content string `json:"content"`
	// The content/body of the scheduled message rendered in HTML.
	RenderedContent string `json:"rendered_content"`
	// The UNIX timestamp for when the message will be sent by the server, in UTC seconds.
	ScheduledDeliveryTimestamp Timestamp `json:"scheduled_delivery_timestamp"`
	// Whether the server has tried to send the scheduled message and it failed to successfully send.  Clients that support unscheduling and editing scheduled messages should display scheduled messages with `\"failed\": true` with an indicator that the server failed to send the message at the scheduled time, so that the user is aware of the failure and can get the content of the scheduled message.  **Changes**: New in Zulip 7.0 (feature level 181).
	Failed bool `json:"failed"`
}

type _ScheduledMessageBase ScheduledMessageBase

// NewScheduledMessageBase instantiates a new ScheduledMessageBase object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScheduledMessageBase(scheduledMessageId int32, recipientType RecipientType, to Recipients, content string, renderedContent string, scheduledDeliveryTimestamp Timestamp, failed bool) *ScheduledMessageBase {
	this := ScheduledMessageBase{}
	this.ScheduledMessageId = scheduledMessageId
	this.Type = recipientType
	this.To = to
	this.Content = content
	this.RenderedContent = renderedContent
	this.ScheduledDeliveryTimestamp = scheduledDeliveryTimestamp
	this.Failed = failed
	return &this
}

// NewScheduledMessageBaseWithDefaults instantiates a new ScheduledMessageBase object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScheduledMessageBaseWithDefaults() *ScheduledMessageBase {
	this := ScheduledMessageBase{}
	return &this
}

// GetScheduledMessageId returns the ScheduledMessageId field value
func (o *ScheduledMessageBase) GetScheduledMessageId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ScheduledMessageId
}

// GetScheduledMessageIdOk returns a tuple with the ScheduledMessageId field value
// and a boolean to check if the value has been set.
func (o *ScheduledMessageBase) GetScheduledMessageIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScheduledMessageId, true
}

// SetScheduledMessageId sets field value
func (o *ScheduledMessageBase) SetScheduledMessageId(v int32) {
	o.ScheduledMessageId = v
}

// GetType returns the Type field value
func (o *ScheduledMessageBase) GetType() RecipientType {
	if o == nil {
		var ret RecipientType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ScheduledMessageBase) GetTypeOk() (*RecipientType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ScheduledMessageBase) SetType(v RecipientType) {
	o.Type = v
}

// GetTo returns the To field value
func (o *ScheduledMessageBase) GetTo() Recipients {
	if o == nil {
		var ret Recipients
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *ScheduledMessageBase) GetToOk() (*Recipients, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *ScheduledMessageBase) SetTo(v Recipients) {
	o.To = v
}

// GetTopic returns the Topic field value if set, zero value otherwise.
func (o *ScheduledMessageBase) GetTopic() string {
	if o == nil || IsNil(o.Topic) {
		var ret string
		return ret
	}
	return *o.Topic
}

// GetTopicOk returns a tuple with the Topic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduledMessageBase) GetTopicOk() (*string, bool) {
	if o == nil || IsNil(o.Topic) {
		return nil, false
	}
	return o.Topic, true
}

// HasTopic returns a boolean if a field has been set.
func (o *ScheduledMessageBase) HasTopic() bool {
	if o != nil && !IsNil(o.Topic) {
		return true
	}

	return false
}

// SetTopic gets a reference to the given string and assigns it to the Topic field.
func (o *ScheduledMessageBase) SetTopic(v string) {
	o.Topic = &v
}

// GetContent returns the Content field value
func (o *ScheduledMessageBase) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *ScheduledMessageBase) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *ScheduledMessageBase) SetContent(v string) {
	o.Content = v
}

// GetRenderedContent returns the RenderedContent field value
func (o *ScheduledMessageBase) GetRenderedContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RenderedContent
}

// GetRenderedContentOk returns a tuple with the RenderedContent field value
// and a boolean to check if the value has been set.
func (o *ScheduledMessageBase) GetRenderedContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RenderedContent, true
}

// SetRenderedContent sets field value
func (o *ScheduledMessageBase) SetRenderedContent(v string) {
	o.RenderedContent = v
}

// GetScheduledDeliveryTimestamp returns the ScheduledDeliveryTimestamp field value
func (o *ScheduledMessageBase) GetScheduledDeliveryTimestamp() Timestamp {
	if o == nil {
		var ret Timestamp
		return ret
	}

	return o.ScheduledDeliveryTimestamp
}

// GetScheduledDeliveryTimestampOk returns a tuple with the ScheduledDeliveryTimestamp field value
// and a boolean to check if the value has been set.
func (o *ScheduledMessageBase) GetScheduledDeliveryTimestampOk() (*Timestamp, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScheduledDeliveryTimestamp, true
}

// SetScheduledDeliveryTimestamp sets field value
func (o *ScheduledMessageBase) SetScheduledDeliveryTimestamp(v Timestamp) {
	o.ScheduledDeliveryTimestamp = v
}

// GetFailed returns the Failed field value
func (o *ScheduledMessageBase) GetFailed() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Failed
}

// GetFailedOk returns a tuple with the Failed field value
// and a boolean to check if the value has been set.
func (o *ScheduledMessageBase) GetFailedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Failed, true
}

// SetFailed sets field value
func (o *ScheduledMessageBase) SetFailed(v bool) {
	o.Failed = v
}

func (o ScheduledMessageBase) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScheduledMessageBase) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scheduled_message_id"] = o.ScheduledMessageId
	toSerialize["type"] = o.Type
	toSerialize["to"] = o.To
	if !IsNil(o.Topic) {
		toSerialize["topic"] = o.Topic
	}
	toSerialize["content"] = o.Content
	toSerialize["rendered_content"] = o.RenderedContent
	toSerialize["scheduled_delivery_timestamp"] = o.ScheduledDeliveryTimestamp
	toSerialize["failed"] = o.Failed
	return toSerialize, nil
}

func (o *ScheduledMessageBase) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scheduled_message_id",
		"type",
		"to",
		"content",
		"rendered_content",
		"scheduled_delivery_timestamp",
		"failed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScheduledMessageBase := _ScheduledMessageBase{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScheduledMessageBase)

	if err != nil {
		return err
	}

	*o = ScheduledMessageBase(varScheduledMessageBase)

	return err
}

type NullableScheduledMessageBase struct {
	value *ScheduledMessageBase
	isSet bool
}

func (v NullableScheduledMessageBase) Get() *ScheduledMessageBase {
	return v.value
}

func (v *NullableScheduledMessageBase) Set(val *ScheduledMessageBase) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduledMessageBase) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduledMessageBase) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduledMessageBase(val *ScheduledMessageBase) *NullableScheduledMessageBase {
	return &NullableScheduledMessageBase{value: val, isSet: true}
}

func (v NullableScheduledMessageBase) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduledMessageBase) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
