/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// SubscriptionDataValue - The new value of the property being modified.  If the property is `\"color\"`, then `value` is a string representing the hex value of the user's display color for the channel. For all other above properties, `value` is a boolean.
type SubscriptionDataValue struct {
	Bool   *bool
	String *string
}

// boolAsSubscriptionDataValue is a convenience function that returns bool wrapped in SubscriptionDataValue
func BoolAsSubscriptionDataValue(v *bool) SubscriptionDataValue {
	return SubscriptionDataValue{
		Bool: v,
	}
}

// stringAsSubscriptionDataValue is a convenience function that returns string wrapped in SubscriptionDataValue
func StringAsSubscriptionDataValue(v *string) SubscriptionDataValue {
	return SubscriptionDataValue{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *SubscriptionDataValue) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Bool
	err = newStrictDecoder(data).Decode(&dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			if err = validator.Validate(dst.Bool); err != nil {
				dst.Bool = nil
			} else {
				match++
			}
		}
	} else {
		dst.Bool = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Bool = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(SubscriptionDataValue)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(SubscriptionDataValue)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SubscriptionDataValue) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SubscriptionDataValue) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.Bool != nil {
		return obj.Bool
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj SubscriptionDataValue) GetActualInstanceValue() interface{} {
	if obj.Bool != nil {
		return *obj.Bool
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableSubscriptionDataValue struct {
	value *SubscriptionDataValue
	isSet bool
}

func (v NullableSubscriptionDataValue) Get() *SubscriptionDataValue {
	return v.value
}

func (v *NullableSubscriptionDataValue) Set(val *SubscriptionDataValue) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionDataValue) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionDataValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionDataValue(val *SubscriptionDataValue) *NullableSubscriptionDataValue {
	return &NullableSubscriptionDataValue{value: val, isSet: true}
}

func (v NullableSubscriptionDataValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionDataValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
