/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// UnmuteUser400Response - struct for UnmuteUser400Response
type UnmuteUser400Response struct {
	CodedError *CodedError
}

// CodedErrorAsUnmuteUser400Response is a convenience function that returns CodedError wrapped in UnmuteUser400Response
func CodedErrorAsUnmuteUser400Response(v *CodedError) UnmuteUser400Response {
	return UnmuteUser400Response{
		CodedError: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *UnmuteUser400Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into CodedError
	err = newStrictDecoder(data).Decode(&dst.CodedError)
	if err == nil {
		jsonCodedError, _ := json.Marshal(dst.CodedError)
		if string(jsonCodedError) == "{}" { // empty struct
			dst.CodedError = nil
		} else {
			if err = validator.Validate(dst.CodedError); err != nil {
				dst.CodedError = nil
			} else {
				match++
			}
		}
	} else {
		dst.CodedError = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.CodedError = nil

		return fmt.Errorf("data matches more than one schema in oneOf(UnmuteUser400Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(UnmuteUser400Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src UnmuteUser400Response) MarshalJSON() ([]byte, error) {
	if src.CodedError != nil {
		return json.Marshal(&src.CodedError)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *UnmuteUser400Response) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.CodedError != nil {
		return obj.CodedError
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj UnmuteUser400Response) GetActualInstanceValue() interface{} {
	if obj.CodedError != nil {
		return *obj.CodedError
	}

	// all schemas are nil
	return nil
}

type NullableUnmuteUser400Response struct {
	value *UnmuteUser400Response
	isSet bool
}

func (v NullableUnmuteUser400Response) Get() *UnmuteUser400Response {
	return v.value
}

func (v *NullableUnmuteUser400Response) Set(val *UnmuteUser400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUnmuteUser400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUnmuteUser400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnmuteUser400Response(val *UnmuteUser400Response) *NullableUnmuteUser400Response {
	return &NullableUnmuteUser400Response{value: val, isSet: true}
}

func (v NullableUnmuteUser400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnmuteUser400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
