/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the UnreadMsgs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UnreadMsgs{}

// UnreadMsgs Present if `message` and `update_message_flags` are both present in `event_types`.  A set of data structures describing the conversations containing the 50000 most recent unread messages the user has received. This will usually contain every unread message the user has received, but clients should support users with even more unread messages (and not hardcode the number 50000).
type UnreadMsgs struct {
	// The total number of unread messages to display. This includes one-on-one and group direct messages, as well as channel messages that are not [muted](/help/mute-a-topic).  **Changes**: Before Zulip 8.0 (feature level 213), the unmute and follow topic features were not handled correctly in calculating this field.
	Count *int32 `json:"count,omitempty"`
	// An array of objects where each object contains details of unread one-on-one direct messages with a specific user.  Note that it is possible for a message that the current user sent to the specified user to be marked as unread and thus appear here.
	Pms []UnreadMsgsPms `json:"pms,omitempty"`
	// An array of dictionaries where each dictionary contains details of all unread messages of a single subscribed channel. This includes muted channels and muted topics, even though those messages are excluded from `count`.  **Changes**: Prior to Zulip 5.0 (feature level 90), these objects included a `sender_ids` property, which listed the set of IDs of users who had sent the unread messages.
	Streams []UnreadMsgsStreams `json:"streams,omitempty"`
	// An array of objects where each object contains details of unread group direct messages with a specific group of users.
	Huddles []UnreadMsgsHuddles `json:"huddles,omitempty"`
	// Array containing the IDs of all unread messages in which the user was mentioned directly, and unread [non-muted](/help/mute-a-topic) messages in which the user was mentioned through a wildcard.  **Changes**: Before Zulip 8.0 (feature level 213), the unmute and follow topic features were not handled correctly in calculating this field.
	Mentions []int32 `json:"mentions,omitempty"`
	// Whether this data set was truncated because the user has too many unread messages. When truncation occurs, only the most recent `MAX_UNREAD_MESSAGES` (currently 50000) messages will be considered when forming this response. When `true`, we recommend that clients display a warning, as they are likely to produce erroneous results until reloaded with the user having fewer than `MAX_UNREAD_MESSAGES` unread messages.  **Changes**: New in Zulip 4.0 (feature level 44).
	OldUnreadsMissing *bool `json:"old_unreads_missing,omitempty"`
}

// NewUnreadMsgs instantiates a new UnreadMsgs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUnreadMsgs() *UnreadMsgs {
	this := UnreadMsgs{}
	return &this
}

// NewUnreadMsgsWithDefaults instantiates a new UnreadMsgs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUnreadMsgsWithDefaults() *UnreadMsgs {
	this := UnreadMsgs{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *UnreadMsgs) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnreadMsgs) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *UnreadMsgs) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *UnreadMsgs) SetCount(v int32) {
	o.Count = &v
}

// GetPms returns the Pms field value if set, zero value otherwise.
func (o *UnreadMsgs) GetPms() []UnreadMsgsPms {
	if o == nil || IsNil(o.Pms) {
		var ret []UnreadMsgsPms
		return ret
	}
	return o.Pms
}

// GetPmsOk returns a tuple with the Pms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnreadMsgs) GetPmsOk() ([]UnreadMsgsPms, bool) {
	if o == nil || IsNil(o.Pms) {
		return nil, false
	}
	return o.Pms, true
}

// HasPms returns a boolean if a field has been set.
func (o *UnreadMsgs) HasPms() bool {
	if o != nil && !IsNil(o.Pms) {
		return true
	}

	return false
}

// SetPms gets a reference to the given []UnreadMsgsPms and assigns it to the Pms field.
func (o *UnreadMsgs) SetPms(v []UnreadMsgsPms) {
	o.Pms = v
}

// GetStreams returns the Streams field value if set, zero value otherwise.
func (o *UnreadMsgs) GetStreams() []UnreadMsgsStreams {
	if o == nil || IsNil(o.Streams) {
		var ret []UnreadMsgsStreams
		return ret
	}
	return o.Streams
}

// GetStreamsOk returns a tuple with the Streams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnreadMsgs) GetStreamsOk() ([]UnreadMsgsStreams, bool) {
	if o == nil || IsNil(o.Streams) {
		return nil, false
	}
	return o.Streams, true
}

// HasStreams returns a boolean if a field has been set.
func (o *UnreadMsgs) HasStreams() bool {
	if o != nil && !IsNil(o.Streams) {
		return true
	}

	return false
}

// SetStreams gets a reference to the given []UnreadMsgsStreams and assigns it to the Streams field.
func (o *UnreadMsgs) SetStreams(v []UnreadMsgsStreams) {
	o.Streams = v
}

// GetHuddles returns the Huddles field value if set, zero value otherwise.
func (o *UnreadMsgs) GetHuddles() []UnreadMsgsHuddles {
	if o == nil || IsNil(o.Huddles) {
		var ret []UnreadMsgsHuddles
		return ret
	}
	return o.Huddles
}

// GetHuddlesOk returns a tuple with the Huddles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnreadMsgs) GetHuddlesOk() ([]UnreadMsgsHuddles, bool) {
	if o == nil || IsNil(o.Huddles) {
		return nil, false
	}
	return o.Huddles, true
}

// HasHuddles returns a boolean if a field has been set.
func (o *UnreadMsgs) HasHuddles() bool {
	if o != nil && !IsNil(o.Huddles) {
		return true
	}

	return false
}

// SetHuddles gets a reference to the given []UnreadMsgsHuddles and assigns it to the Huddles field.
func (o *UnreadMsgs) SetHuddles(v []UnreadMsgsHuddles) {
	o.Huddles = v
}

// GetMentions returns the Mentions field value if set, zero value otherwise.
func (o *UnreadMsgs) GetMentions() []int32 {
	if o == nil || IsNil(o.Mentions) {
		var ret []int32
		return ret
	}
	return o.Mentions
}

// GetMentionsOk returns a tuple with the Mentions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnreadMsgs) GetMentionsOk() ([]int32, bool) {
	if o == nil || IsNil(o.Mentions) {
		return nil, false
	}
	return o.Mentions, true
}

// HasMentions returns a boolean if a field has been set.
func (o *UnreadMsgs) HasMentions() bool {
	if o != nil && !IsNil(o.Mentions) {
		return true
	}

	return false
}

// SetMentions gets a reference to the given []int32 and assigns it to the Mentions field.
func (o *UnreadMsgs) SetMentions(v []int32) {
	o.Mentions = v
}

// GetOldUnreadsMissing returns the OldUnreadsMissing field value if set, zero value otherwise.
func (o *UnreadMsgs) GetOldUnreadsMissing() bool {
	if o == nil || IsNil(o.OldUnreadsMissing) {
		var ret bool
		return ret
	}
	return *o.OldUnreadsMissing
}

// GetOldUnreadsMissingOk returns a tuple with the OldUnreadsMissing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UnreadMsgs) GetOldUnreadsMissingOk() (*bool, bool) {
	if o == nil || IsNil(o.OldUnreadsMissing) {
		return nil, false
	}
	return o.OldUnreadsMissing, true
}

// HasOldUnreadsMissing returns a boolean if a field has been set.
func (o *UnreadMsgs) HasOldUnreadsMissing() bool {
	if o != nil && !IsNil(o.OldUnreadsMissing) {
		return true
	}

	return false
}

// SetOldUnreadsMissing gets a reference to the given bool and assigns it to the OldUnreadsMissing field.
func (o *UnreadMsgs) SetOldUnreadsMissing(v bool) {
	o.OldUnreadsMissing = &v
}

func (o UnreadMsgs) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UnreadMsgs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Pms) {
		toSerialize["pms"] = o.Pms
	}
	if !IsNil(o.Streams) {
		toSerialize["streams"] = o.Streams
	}
	if !IsNil(o.Huddles) {
		toSerialize["huddles"] = o.Huddles
	}
	if !IsNil(o.Mentions) {
		toSerialize["mentions"] = o.Mentions
	}
	if !IsNil(o.OldUnreadsMissing) {
		toSerialize["old_unreads_missing"] = o.OldUnreadsMissing
	}
	return toSerialize, nil
}

type NullableUnreadMsgs struct {
	value *UnreadMsgs
	isSet bool
}

func (v NullableUnreadMsgs) Get() *UnreadMsgs {
	return v.value
}

func (v *NullableUnreadMsgs) Set(val *UnreadMsgs) {
	v.value = val
	v.isSet = true
}

func (v NullableUnreadMsgs) IsSet() bool {
	return v.isSet
}

func (v *NullableUnreadMsgs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUnreadMsgs(val *UnreadMsgs) *NullableUnreadMsgs {
	return &NullableUnreadMsgs{value: val, isSet: true}
}

func (v NullableUnreadMsgs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUnreadMsgs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
