/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateSubscriptionSetting type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSubscriptionSetting{}

// UpdateSubscriptionSetting struct for UpdateSubscriptionSetting
type UpdateSubscriptionSetting struct {
	// The unique ID of a channel.
	StreamId int32 `json:"stream_id"`
	// One of the channel properties described below:  - `\"color\"`: The hex value of the user's display color for the channel.  - `\"is_muted\"`: Whether the channel is [muted](zulip.com/help/mute-a-channel.<br>   **Changes**: As of Zulip 6.0 (feature level 139), updating either   `\"is_muted\"` or `\"in_home_view\"` generates two [subscription update   events](zulip.com/api/get-events#subscription-update, one for each property,   that are sent to clients. Prior to this feature level, updating either   property only generated a subscription update event for   `\"in_home_view\"`. <br>   Prior to Zulip 2.1.0, this feature was represented   by the more confusingly named `\"in_home_view\"` (with the   opposite value: `in_home_view=!is_muted`); for   backwards-compatibility, modern Zulip still accepts that property.  - `\"pin_to_top\"`: Whether to pin the channel at the top of the channel list.  - `\"desktop_notifications\"`: Whether to show desktop notifications   for all messages sent to the channel.  - `\"audible_notifications\"`: Whether to play a sound   notification for all messages sent to the channel.  - `\"push_notifications\"`: Whether to trigger a mobile push   notification for all messages sent to the channel.  - `\"email_notifications\"`: Whether to trigger an email   notification for all messages sent to the channel.  - `\"wildcard_mentions_notify\"`: Whether wildcard mentions trigger   notifications as though they were personal mentions in this channel.
	Property string                `json:"property"`
	Value    SubscriptionDataValue `json:"value"`
}

type _UpdateSubscriptionSetting UpdateSubscriptionSetting

// NewUpdateSubscriptionSetting instantiates a new UpdateSubscriptionSetting object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSubscriptionSetting(streamId int32, property string, value SubscriptionDataValue) *UpdateSubscriptionSetting {
	this := UpdateSubscriptionSetting{}
	this.StreamId = streamId
	this.Property = property
	this.Value = value
	return &this
}

// NewUpdateSubscriptionSettingWithDefaults instantiates a new UpdateSubscriptionSetting object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSubscriptionSettingWithDefaults() *UpdateSubscriptionSetting {
	this := UpdateSubscriptionSetting{}
	return &this
}

// GetStreamId returns the StreamId field value
func (o *UpdateSubscriptionSetting) GetStreamId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StreamId
}

// GetStreamIdOk returns a tuple with the StreamId field value
// and a boolean to check if the value has been set.
func (o *UpdateSubscriptionSetting) GetStreamIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StreamId, true
}

// SetStreamId sets field value
func (o *UpdateSubscriptionSetting) SetStreamId(v int32) {
	o.StreamId = v
}

// GetProperty returns the Property field value
func (o *UpdateSubscriptionSetting) GetProperty() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Property
}

// GetPropertyOk returns a tuple with the Property field value
// and a boolean to check if the value has been set.
func (o *UpdateSubscriptionSetting) GetPropertyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Property, true
}

// SetProperty sets field value
func (o *UpdateSubscriptionSetting) SetProperty(v string) {
	o.Property = v
}

// GetValue returns the Value field value
func (o *UpdateSubscriptionSetting) GetValue() SubscriptionDataValue {
	if o == nil {
		var ret SubscriptionDataValue
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *UpdateSubscriptionSetting) GetValueOk() (*SubscriptionDataValue, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *UpdateSubscriptionSetting) SetValue(v SubscriptionDataValue) {
	o.Value = v
}

func (o UpdateSubscriptionSetting) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSubscriptionSetting) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["stream_id"] = o.StreamId
	toSerialize["property"] = o.Property
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *UpdateSubscriptionSetting) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"stream_id",
		"property",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateSubscriptionSetting := _UpdateSubscriptionSetting{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateSubscriptionSetting)

	if err != nil {
		return err
	}

	*o = UpdateSubscriptionSetting(varUpdateSubscriptionSetting)

	return err
}

type NullableUpdateSubscriptionSetting struct {
	value *UpdateSubscriptionSetting
	isSet bool
}

func (v NullableUpdateSubscriptionSetting) Get() *UpdateSubscriptionSetting {
	return v.value
}

func (v *NullableUpdateSubscriptionSetting) Set(val *UpdateSubscriptionSetting) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSubscriptionSetting) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSubscriptionSetting) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSubscriptionSetting(val *UpdateSubscriptionSetting) *NullableUpdateSubscriptionSetting {
	return &NullableUpdateSubscriptionSetting{value: val, isSet: true}
}

func (v NullableUpdateSubscriptionSetting) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSubscriptionSetting) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
