/*
Zulip REST API

Powerful open source group chat

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
)

// checks if the UpdateDisplaySettingsEvent7StreamsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDisplaySettingsEvent7StreamsInner{}

// UpdateDisplaySettingsEvent7StreamsInner struct for UpdateDisplaySettingsEvent7StreamsInner
type UpdateDisplaySettingsEvent7StreamsInner struct {
	// ID of the deleted channel.
	StreamId *int32 `json:"stream_id,omitempty"`
}

// NewUpdateDisplaySettingsEvent7StreamsInner instantiates a new UpdateDisplaySettingsEvent7StreamsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDisplaySettingsEvent7StreamsInner() *UpdateDisplaySettingsEvent7StreamsInner {
	this := UpdateDisplaySettingsEvent7StreamsInner{}
	return &this
}

// NewUpdateDisplaySettingsEvent7StreamsInnerWithDefaults instantiates a new UpdateDisplaySettingsEvent7StreamsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDisplaySettingsEvent7StreamsInnerWithDefaults() *UpdateDisplaySettingsEvent7StreamsInner {
	this := UpdateDisplaySettingsEvent7StreamsInner{}
	return &this
}

// GetStreamId returns the StreamId field value if set, zero value otherwise.
func (o *UpdateDisplaySettingsEvent7StreamsInner) GetStreamId() int32 {
	if o == nil || IsNil(o.StreamId) {
		var ret int32
		return ret
	}
	return *o.StreamId
}

// GetStreamIdOk returns a tuple with the StreamId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDisplaySettingsEvent7StreamsInner) GetStreamIdOk() (*int32, bool) {
	if o == nil || IsNil(o.StreamId) {
		return nil, false
	}
	return o.StreamId, true
}

// HasStreamId returns a boolean if a field has been set.
func (o *UpdateDisplaySettingsEvent7StreamsInner) HasStreamId() bool {
	if o != nil && !IsNil(o.StreamId) {
		return true
	}

	return false
}

// SetStreamId gets a reference to the given int32 and assigns it to the StreamId field.
func (o *UpdateDisplaySettingsEvent7StreamsInner) SetStreamId(v int32) {
	o.StreamId = &v
}

func (o UpdateDisplaySettingsEvent7StreamsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDisplaySettingsEvent7StreamsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.StreamId) {
		toSerialize["stream_id"] = o.StreamId
	}
	return toSerialize, nil
}

type NullableUpdateDisplaySettingsEvent7StreamsInner struct {
	value *UpdateDisplaySettingsEvent7StreamsInner
	isSet bool
}

func (v NullableUpdateDisplaySettingsEvent7StreamsInner) Get() *UpdateDisplaySettingsEvent7StreamsInner {
	return v.value
}

func (v *NullableUpdateDisplaySettingsEvent7StreamsInner) Set(val *UpdateDisplaySettingsEvent7StreamsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDisplaySettingsEvent7StreamsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDisplaySettingsEvent7StreamsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDisplaySettingsEvent7StreamsInner(val *UpdateDisplaySettingsEvent7StreamsInner) *NullableUpdateDisplaySettingsEvent7StreamsInner {
	return &NullableUpdateDisplaySettingsEvent7StreamsInner{value: val, isSet: true}
}

func (v NullableUpdateDisplaySettingsEvent7StreamsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDisplaySettingsEvent7StreamsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
