/*
Zulip REST API

Powerful open source group chat 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package models

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateMessageFlags200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMessageFlags200Response{}

// UpdateMessageFlags200Response struct for UpdateMessageFlags200Response
type UpdateMessageFlags200Response struct {
	Result interface{} `json:"result"`
	Msg interface{} `json:"msg"`
	IgnoredParametersUnsupported interface{} `json:"ignored_parameters_unsupported,omitempty"`
	// An array with the IDs of the modified messages. 
	Messages []int32 `json:"messages,omitempty"`
	// Only present if the flag is `read` and the operation is `remove`.  Zulip has an invariant that all unread messages must be in channels the user is subscribed to. This field will contain a list of the channels whose messages were skipped to mark as unread because the user is not subscribed to them.  **Changes**: New in Zulip 10.0 (feature level 355). 
	IgnoredBecauseNotSubscribedChannels []int32 `json:"ignored_because_not_subscribed_channels,omitempty"`
}

type _UpdateMessageFlags200Response UpdateMessageFlags200Response

// NewUpdateMessageFlags200Response instantiates a new UpdateMessageFlags200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMessageFlags200Response(result interface{}, msg interface{}) *UpdateMessageFlags200Response {
	this := UpdateMessageFlags200Response{}
	this.Result = result
	this.Msg = msg
	return &this
}

// NewUpdateMessageFlags200ResponseWithDefaults instantiates a new UpdateMessageFlags200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMessageFlags200ResponseWithDefaults() *UpdateMessageFlags200Response {
	this := UpdateMessageFlags200Response{}
	return &this
}

// GetResult returns the Result field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *UpdateMessageFlags200Response) GetResult() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateMessageFlags200Response) GetResultOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *UpdateMessageFlags200Response) SetResult(v interface{}) {
	o.Result = v
}

// GetMsg returns the Msg field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *UpdateMessageFlags200Response) GetMsg() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Msg
}

// GetMsgOk returns a tuple with the Msg field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateMessageFlags200Response) GetMsgOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return &o.Msg, true
}

// SetMsg sets field value
func (o *UpdateMessageFlags200Response) SetMsg(v interface{}) {
	o.Msg = v
}

// GetIgnoredParametersUnsupported returns the IgnoredParametersUnsupported field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateMessageFlags200Response) GetIgnoredParametersUnsupported() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.IgnoredParametersUnsupported
}

// GetIgnoredParametersUnsupportedOk returns a tuple with the IgnoredParametersUnsupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateMessageFlags200Response) GetIgnoredParametersUnsupportedOk() (*interface{}, bool) {
	if o == nil || IsNil(o.IgnoredParametersUnsupported) {
		return nil, false
	}
	return &o.IgnoredParametersUnsupported, true
}

// HasIgnoredParametersUnsupported returns a boolean if a field has been set.
func (o *UpdateMessageFlags200Response) HasIgnoredParametersUnsupported() bool {
	if o != nil && !IsNil(o.IgnoredParametersUnsupported) {
		return true
	}

	return false
}

// SetIgnoredParametersUnsupported gets a reference to the given interface{} and assigns it to the IgnoredParametersUnsupported field.
func (o *UpdateMessageFlags200Response) SetIgnoredParametersUnsupported(v interface{}) {
	o.IgnoredParametersUnsupported = v
}

// GetMessages returns the Messages field value if set, zero value otherwise.
func (o *UpdateMessageFlags200Response) GetMessages() []int32 {
	if o == nil || IsNil(o.Messages) {
		var ret []int32
		return ret
	}
	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateMessageFlags200Response) GetMessagesOk() ([]int32, bool) {
	if o == nil || IsNil(o.Messages) {
		return nil, false
	}
	return o.Messages, true
}

// HasMessages returns a boolean if a field has been set.
func (o *UpdateMessageFlags200Response) HasMessages() bool {
	if o != nil && !IsNil(o.Messages) {
		return true
	}

	return false
}

// SetMessages gets a reference to the given []int32 and assigns it to the Messages field.
func (o *UpdateMessageFlags200Response) SetMessages(v []int32) {
	o.Messages = v
}

// GetIgnoredBecauseNotSubscribedChannels returns the IgnoredBecauseNotSubscribedChannels field value if set, zero value otherwise.
func (o *UpdateMessageFlags200Response) GetIgnoredBecauseNotSubscribedChannels() []int32 {
	if o == nil || IsNil(o.IgnoredBecauseNotSubscribedChannels) {
		var ret []int32
		return ret
	}
	return o.IgnoredBecauseNotSubscribedChannels
}

// GetIgnoredBecauseNotSubscribedChannelsOk returns a tuple with the IgnoredBecauseNotSubscribedChannels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateMessageFlags200Response) GetIgnoredBecauseNotSubscribedChannelsOk() ([]int32, bool) {
	if o == nil || IsNil(o.IgnoredBecauseNotSubscribedChannels) {
		return nil, false
	}
	return o.IgnoredBecauseNotSubscribedChannels, true
}

// HasIgnoredBecauseNotSubscribedChannels returns a boolean if a field has been set.
func (o *UpdateMessageFlags200Response) HasIgnoredBecauseNotSubscribedChannels() bool {
	if o != nil && !IsNil(o.IgnoredBecauseNotSubscribedChannels) {
		return true
	}

	return false
}

// SetIgnoredBecauseNotSubscribedChannels gets a reference to the given []int32 and assigns it to the IgnoredBecauseNotSubscribedChannels field.
func (o *UpdateMessageFlags200Response) SetIgnoredBecauseNotSubscribedChannels(v []int32) {
	o.IgnoredBecauseNotSubscribedChannels = v
}

func (o UpdateMessageFlags200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMessageFlags200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Result != nil {
		toSerialize["result"] = o.Result
	}
	if o.Msg != nil {
		toSerialize["msg"] = o.Msg
	}
	if o.IgnoredParametersUnsupported != nil {
		toSerialize["ignored_parameters_unsupported"] = o.IgnoredParametersUnsupported
	}
	if !IsNil(o.Messages) {
		toSerialize["messages"] = o.Messages
	}
	if !IsNil(o.IgnoredBecauseNotSubscribedChannels) {
		toSerialize["ignored_because_not_subscribed_channels"] = o.IgnoredBecauseNotSubscribedChannels
	}
	return toSerialize, nil
}

func (o *UpdateMessageFlags200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"result",
		"msg",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateMessageFlags200Response := _UpdateMessageFlags200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateMessageFlags200Response)

	if err != nil {
		return err
	}

	*o = UpdateMessageFlags200Response(varUpdateMessageFlags200Response)

	return err
}

type NullableUpdateMessageFlags200Response struct {
	value *UpdateMessageFlags200Response
	isSet bool
}

func (v NullableUpdateMessageFlags200Response) Get() *UpdateMessageFlags200Response {
	return v.value
}

func (v *NullableUpdateMessageFlags200Response) Set(val *UpdateMessageFlags200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMessageFlags200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMessageFlags200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMessageFlags200Response(val *UpdateMessageFlags200Response) *NullableUpdateMessageFlags200Response {
	return &NullableUpdateMessageFlags200Response{value: val, isSet: true}
}

func (v NullableUpdateMessageFlags200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMessageFlags200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


