name: Zulip Client Integration

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: integration-${{ github.ref }}
  cancel-in-progress: false


jobs:
  integration:
    name: Go tests against Zulip ${{ matrix.zulip-branch }}
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        zulip-branch:
          - main
          - 7.x
    env:
      GO111MODULE: "on"
      GOFLAGS: "-trimpath"
      ZULIP_TEST_SITE: http://127.0.0.1:9991
      ZULIP_DEV_LOG: ${{ github.workspace }}/zulip-dev.log
    steps:
      - name: Checkout go-zulip
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.2"

      - name: Cache Go build and modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Check gofmt formatting
        run: |
          set -euo pipefail
          files=$(git ls-files '*.go')
          if [ -z "$files" ]; then
            exit 0
          fi
          out=$(gofmt -l $files)
          if [ -n "$out" ]; then
            echo "The following files need gofmt -w -s:" >&2
            echo "$out" >&2
            exit 1
          fi

      - name: Check goimports formatting
        run: |
          set -euo pipefail
          files=$(git ls-files '*.go')
          if [ -z "$files" ]; then
            exit 0
          fi
          diff=$(go run golang.org/x/tools/cmd/goimports@latest -d $files)
          if [ -n "$diff" ]; then
            echo "$diff"
            echo "Go files require goimports formatting" >&2
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Run staticcheck
        run: go run honnef.co/go/tools/cmd/staticcheck@2025.1.1 ./...

      - name: Run fast model/unit tests
        run: ./scripts/run-model-tests.sh

      - name: Build go-zulip
        run: go build ./...

      - name: Checkout Zulip server ${{ matrix.zulip-branch }}
        run: git clone --depth 1 --branch "${{ matrix.zulip-branch }}" https://github.com/zulip/zulip.git /tmp/zulip-server

      - name: Provision Zulip dev server
        working-directory: /tmp/zulip-server
        run: |
          sudo apt-get update
          sudo apt-get install -y rabbitmq-server redis-server memcached postgresql
          sudo service postgresql start
          sudo service rabbitmq-server start
          sudo service redis-server start
          sudo service memcached start
          ./tools/provision --force

      - name: Start Zulip dev server
        working-directory: /tmp/zulip-server
        run: |
          nohup ./tools/run-dev.sh >"${ZULIP_DEV_LOG}" 2>&1 &
          echo $! > /tmp/zulip-dev.pid

      - name: Wait for Zulip dev server to become ready
        run: |
          echo "Waiting for Zulip server at ${ZULIP_TEST_SITE}"
          for attempt in {1..60}; do
            if curl --silent --show-error --fail "${ZULIP_TEST_SITE}/api/v1/server_settings" >/dev/null; then
              echo "Zulip is up"
              exit 0
            fi
            echo "Attempt ${attempt}: Zulip not ready yet"
            sleep 10
          done
          echo "Zulip server failed to start" >&2
          exit 1

      - name: Run go test suite with coverage
        env:
          ZULIP_TEST_SITE: http://127.0.0.1:9991
        run: go test ./zulip -covermode=atomic -coverprofile=coverage.out -timeout 60m

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.out
          flags: integration
          name: integration-${{ matrix.zulip-branch }}
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          ZULIP_BRANCH: ${{ matrix.zulip-branch }}

      - name: Show Zulip server logs on failure
        if: failure()
        run: |
          echo "===== zulip-dev.log ====="
          cat "${ZULIP_DEV_LOG}" || true

      - name: Upload Zulip server log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zulip-dev-log-${{ matrix.zulip-branch }}
          path: ${{ env.ZULIP_DEV_LOG }}
          if-no-files-found: ignore

      - name: Stop Zulip dev server
        if: always()
        run: |
          if [ -f /tmp/zulip-dev.pid ]; then
            sudo kill "$(cat /tmp/zulip-dev.pid)" || true
          fi
          sudo pkill -f run-dev.sh || true

