name: Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: arc-runner-set

    steps:
      - name: Checkout go-zulip
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.2"

      - name: Lint
        uses: golangci/golangci-lint-action@v8

  integration:
    name: Test (Zulip ${{ matrix.zulip_ref }})
    runs-on: arc-runner-set
    container: zulip/ci:jammy
    strategy:
      matrix:
        zulip_ref:
          - main
          - 11.x
          - 10.x
          - 9.x
      fail-fast: false
    env:
      GO111MODULE: "on"
      GOFLAGS: "-trimpath"
      ZULIP_TEST_SITE: http://localhost:9991
      ZULIP_DEV_LOG: ${{ github.workspace }}/zulip-dev.log
    needs: lint
    steps:
      - name: Checkout go-zulip
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.2"

      - name: Start Zulip
        uses:  ./.github/actions/provision-zulip
        with:
          zulip_ref: ${{ matrix.zulip_ref }}

      - name: Give Zulip some time to settle
        shell: bash
        run: |
          echo "Waiting 15 seconds for Zulip to settle..."
          sleep 15

      - name: Run go test suite with coverage
        run: go test ./... -covermode=atomic -coverprofile=coverage.out -timeout 60m

      - name: Upload coverage to Codecov
        if: success() && github.ref == 'refs/heads/main'
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.out
          flags: integration
          name: integration-${{ matrix.zulip_ref }}
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          ZULIP_BRANCH: ${{ matrix.zulip_ref }}

  godoc:
    name: Godoc
    runs-on: arc-runner-set

    steps:
      - name: Checkout go-zulip
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.2"

      - name: Generate godoc
        run: |
          mkdir -p ./docs/godoc
          go install golang.org/x/tools/cmd/godoc@latest
          godoc -url="/pkg/github.com/tum-zulip/go-zulip/zulip/" > ./docs/godoc/index.html

      - name: Upload godoc artifact
        uses: actions/upload-artifact@v4
        with:
          name: godoc-html
          path: ./docs/godoc/
          retention-days: 7
